Protobuf support (draft)
github/codeql-go pull request #285
Opened 2020-08-11 17:31 UTC by smowton

This isn't quite done yet, but it's close enough that I'd appreciate feedback on the trickier points here.

Problems to overcome:
* Desire to taint the output of Marshal based on transitive field / array-element writes (e.g. `msg.SubMessage.RepeatedMessage[2].Description = somethingNasty()`)
* Desire to propagate taint properly across `Merge` and `Clone`, which should copy taint from corresponding field to field
* Desire to support `MarshalOptions.MarshalState`, which takes its message from and returns its buffer in a struct field

Current approach:
* The read-side of MarshalOptions.MarshalState precisely models the field the taint is consumed from. The write-side simply taints the whole output, since it only has one field, and relies on the default taint rule that object taint implies field-read taint.
* Messages are tainted as a whole, which simplifies Merge and Clone operations but complicates the additional steps needed to convey taint from a field-write to the underlying SSA variable (I extend SsaWithFields to navigate the access path consisting of field-accesses and element-reads, but this might not be appropriate and we might need a separate mechanism for this). This also could produce false-positives by spreading taint to untainted fields (and of course array elements, but this is more ordinary); whether this is a practical problem depends on whether people like to use their protobuf structs as working data structures, or if they simply populate them immediately before serialisation (i.e., if the fields are in practice write-only)

Possible changes:
* Given I gave up on field-sensitive modelling of Marshal for the time being, we could in the same spirit throw away the complicated MarshalOptions.MarshalState stuff and simply propagate taint from a Message to a MarshalInput struct.
* Extending SsaWithFields as I have done might be inappropriate because its `similar()` method will currently conflate access paths using differing indices. In that case we need a different way to walk down an access path consisting of field-read and element-read operations to taint the bottom Message in the pile.
* If any of this is too contentious I could back off some of today's experiments and simply PR the easy partial support and follow up with either custom hackery as seen here, or with a more general mechanism to state a function model that deals in access paths rather than simply direct inputs and outputs.

2020-08-12 11:58 UTC, smowton commented
I added further tests including ones exhibiting inaccuracy of the current implementation.

TODO:
* Clean up the test directory, which contains many redundant copies of the protoc output and some debugging queries that don't need to be in the final PR
* Change note

2020-08-12 11:59 UTC, smowton commented
I also note a search of Github suggests this is now the only user of MarshalOptions.MarshalState that exists (the API was only introduced earlier this year)

2020-08-12 14:28 UTC, smowton commented
TODOs done apart from the change-note, which I'll write last so as not to forget to update it.

I gave up on modelling UnmarshalOptions.UnmarshalState, as that would need to propagate taint like

```
func testUnmarshalOptions() {
	options := proto.UnmarshalOptions{}

	untrustedSerialized := getUntrustedBytes()
	query := &query.Query{}

	state := protoiface.UnmarshalInput {
		Message: query.ProtoReflect(),
		Buf: untrustedSerialized,
		Flags: 0,
		Resolver: nil,
	}

	options.UnmarshalState(state)
	
	sinkString(query.Description) // BAD
}
```

That would need us to work backwards from the input struct to its field, *and then* from `.ProtoReflect()` call to the query it actually refers to. Ultimately doable but painful.

2020-08-12 14:41 UTC, owen-mc commented
> I also note a search of Github suggests this is now the only user of MarshalOptions.MarshalState that exists (the API was only introduced earlier this year)

But note that github code search is pretty unreliable.

2020-08-14 10:43 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +   * Additional taint-flow step modelling flow from MarshalInput.Message to MarshalOutput,
```suggestion
   * Additional taint-flow step modelling flow from `MarshalInput.Message` to `MarshalOutput`,
```

2020-08-14 10:43 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +   * mediated by a MarshalOptions.MarshalState call.
```suggestion
   * mediated by a `MarshalOptions.MarshalState` call.
```

2020-08-14 10:44 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +   * Note we can taint the whole MarshalOutput as it only has one field (Buf), and taint-
```suggestion
   * Note we can taint the whole `MarshalOutput` as it only has one field (`Buf`), and taint-
```

2020-08-14 10:48 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +          marshalInput.asExpr().getGlobalValueNumber() and
```suggestion
        globalValueNumber(passedMarshalInput) = globalValueNumber(marshalInput) and
```

Alternatively, you can replace the single use of `passedMarshalInput` with `globalValueNumber(marshalInput).getANode()`.

2020-08-14 10:54 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +          accessPath.getBaseVariable().getAUse()
```suggestion
        succ = DataFlow::ssaNode(accessPath.getBaseVariable())
```

2020-08-14 16:49 UTC, max-schaefer commented
> Desire to propagate taint properly across Merge and Clone, which should copy taint from corresponding field to field

I seem to vaguely remember that we don't do field-sensitive propagation through taint, only through plain data flow. In other words, if we know that there is data flow between `x` and y`, then we will conclude that the same is true for `x.f` and `y.f`. If, on the other hand, all we know is that taint is propagated from `x` to `y`, we don't do the same. Have you tried promoting your models of `Merge` and `Clone` from `TaintTracking::FunctionModel`s to `DataFlow::FunctionModel`s to see if that helps?

2020-08-14 17:46 UTC, smowton commented
Distcompare result was unremarkable

2020-08-19 11:02 UTC, sauyon commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +      exists(SsaWithFieldsAndElements accessPath |
Though I think `SsaWithFieldsAndElements` might be useful elsewhere, I think it might also be useful to have a superclass for instructions / nodes / exprs that have a "base" so you can just use `.getBase()+` here.

2020-08-20 11:06 UTC, smowton commented on ql/src/semmle/go/dataflow/SSA.qll
> +   * Gets the SSA variable corresponding to the base of this SSA variable with fields and/or array elements.
No, I forgot they were a first-class type. Looks like the Go implementation does indeed produce maps too -- I'll add this.

2020-08-20 11:10 UTC, smowton commented on ql/src/semmle/go/dataflow/SSA.qll
> +  TElementStep(SsaWithFieldsAndElements base, IR::Instruction idx) {
You mean as an alternative to `IR::Instruction` as the representation of the index? That does sound better, I was just worried that because GVN analysis is based on the SSA representation this would invert the pass order.

2020-08-20 11:10 UTC, smowton commented on ql/src/semmle/go/dataflow/SSA.qll
> +      result = base.getType().getUnderlyingType().(ArrayType).getElementType()
Slices and maps agreed -- I'll do both.

2020-08-20 11:11 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +              inputMessageField(), pred) and
Yeah, this is probably overkill.

2020-08-20 11:12 UTC, smowton commented on ql/test/library-tests/semmle/go/frameworks/Protobuf/testDeprecatedApi.go
> +package main
Sure, sounds like a good step, I'll have a go

2020-08-20 11:15 UTC, smowton commented
Pushed fixes for the simple review comments, will get to Sauyon's improvements this afternoon.

2020-08-27 16:53 UTC, smowton commented
@max-schaefer @sauyon I've pushed the two big changes: support for maps, and using getBase() instead of SsaWithFieldsAndElements, as the top two commits. If you like the getBase solution better I'll drop the SsaWithFieldsAndElements commit.

2020-09-03 13:40 UTC, max-schaefer commented
> If you like the getBase solution better I'll drop the SsaWithFieldsAndElements commit.

Yes, I much prefer it. I hadn't realised (or perhaps had forgotten) that we weren't matching up the series of field and element accesses between write and read anyway, so there really isn't much point to capturing it in a special data structure.

2020-09-03 14:04 UTC, max-schaefer requested changes
A few more suggestions. IIUC, moving away from `SsaWithFieldsAndElements` should simplify this considerably, which I look forward to.

2020-09-03 14:04 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +      exists(DataFlow::ReadNode base | succ = DataFlow::getUnderlyingNode(base) |
Does this do the right thing? Shouldn't `succ` rather be the post-update node whose pre-update is the base of the write?

2020-09-03 14:04 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +        [succ.getType(), succ.getType().getPointerType()] instanceof MessageType
Looks like we might need a type that allows us to uniformly treat element/field _writes_ as well as reads?

2020-09-03 16:10 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +              inputMessageField(), pred) and
For this case the fields are an incoming byte buffer, the message to be serialized into it, and some flags, so I don't think there's a strong chance of a false positive.

2020-09-03 16:29 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +        [succ.getType(), succ.getType().getPointerType()] instanceof MessageType
Combined these by introducing `writesComponent`

2020-09-03 16:30 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +      exists(DataFlow::ReadNode base | succ = DataFlow::getUnderlyingNode(base) |
Adding the post-update node stuff loses you cases like `x[0].y = value`, because `x` does not have a post-update node. What do you recommend here?

2020-09-03 16:30 UTC, smowton commented
@max-schaefer most suggestions implemented except as noted

2020-09-03 18:47 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +      exists(DataFlow::ReadNode base | succ = DataFlow::getUnderlyingNode(base) |
Oh, hm, I see. But what's the use of having a step from `value` to `x` in this example? There isn't any outgoing flow from `x`, is there? So wouldn't the flow get stuck?

2020-09-04 10:43 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +      exists(DataFlow::ReadNode base | succ = DataFlow::getUnderlyingNode(base) |
Aha, looks like I had a pair of nearly-cancelling bugs -- the default taint rule for derefs was conveying the taint from the operand of an implicit deref (here `x`) back out to the deref (implicit `*x`) and then to the post-update node of `x` -- which *did* exist because of the implicit deref operation.

Only for complex cases I was missing the post-update node's existence because I was failing to account for implicit derefs happening during `x[0].y`.

I've now fixed that omission and introduced a cast to PostUpdateNode as expected. This means that this case works, due to an implicit deref of `x` at the top level:
```
x := &SomeType{}
x.y[z].w[v].a = getTaint()
```
But this case doesn't, as `x` doesn't have a post-update node:
```
x := SomeType{}
x.y[z].w[v].a = getTaint()
```

2020-09-04 11:38 UTC, smowton commented
@max-schaefer pushed a fix to the post-update node problems, and an extra probably controversial commit that bypasses `PostUpdateNode` so we can update objects with longer access paths.

2020-09-04 12:48 UTC, max-schaefer commented on extractor/dbscheme/tables.go
> +var ComponentAccessExpr = NewUnionType("@componentaccessexpr", NodeType)
Oh, sorry, I didn't mean to suggest that you should do a dbscheme update. That's overkill, and also not the right level of abstraction since a `@selectorexpr` can be any number of things, not just a field access.

I meant to suggest that you should do this at the QL level:

```ql
class ComponentAccess extends Expr {
  ComponentAccess() {
    this instanceof @indexexpr or
     // slightly more complicated reasoning about selectors omitted
  }
}
```

2020-09-04 12:49 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +  DataFlow::Node getBaseLookingThroughDerefs(DataFlow::ComponentReadNode node) {
Does this perhaps suggest that we want pointer-dereferences to also be component reads? (In which case it's not a great name...)

2020-09-04 12:50 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +  DataFlow::Node getPreUpdateNode(DataFlow::Node node) {
I would support extending `PostUpdateNode`s to do this always. For example, in an assignment

```go
x.y.z = 0
```

I think it makes sense to consider that both `x` and `x.y` have been changed, and hence should have post-update nodes.

2020-09-04 12:50 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +  DataFlow::Node getPreUpdateNode(DataFlow::Node node) {
Note that this is a somewhat subtle change and would need careful benchmarking.

2020-09-04 12:54 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +  DataFlow::Node getPreUpdateNode(DataFlow::Node node) {
This will certainly have unforeseen consequences. Let's do it, but as its own subsequent PR?

2020-09-04 12:58 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +  DataFlow::Node getPreUpdateNode(DataFlow::Node node) {
How about trying it out in a separate PR _first_? This approach is so ugly that I only want to accept it into `main` once alternatives have been tried and found wanting.

2020-09-04 14:12 UTC, smowton commented on extractor/dbscheme/tables.go
> +var ComponentAccessExpr = NewUnionType("@componentaccessexpr", NodeType)
Reverted the DB and Expr parts of this

2020-09-04 14:13 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +  DataFlow::Node getBaseLookingThroughDerefs(DataFlow::ComponentReadNode node) {
I'll pass on this for now, I think derefs and field-/element-accesses differ enough that I don't think they should have a common superclass

2020-09-04 14:13 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +  DataFlow::Node getPreUpdateNode(DataFlow::Node node) {
Dropped this commit for now

2020-09-04 14:30 UTC, smowton commented
@max-schaefer dropped the post-update node changes to pursue in a future PR, and reverted the DB and Expr.qll changes.

2020-09-04 14:43 UTC, max-schaefer requested changes
OK, this is looking quite reasonable now. I think it would be worth doing a dist-compare, though, just to make sure.

2020-09-04 14:43 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +    if node.getBase() instanceof DataFlow::PointerDereferenceNode
Perhaps pull `node.getBase()` out into a variable. While it may not affect performance much in this case, it's generally best to keep `if` conditions as simple as possible.

2020-09-04 14:43 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +  DataFlow::Node getBaseLookingThroughDerefs(DataFlow::ComponentReadNode node) {
Perhaps would could make this predicate private?

2020-09-04 14:43 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +            .writesField(marshalInput.(DataFlow::PostUpdateNode).getPreUpdateNode(),
Perhaps it would be easier to just declare `marshalInput` as a `PostUpdateNode`? Then you don't need the cast.

2020-09-04 16:00 UTC, smowton commented on ql/src/semmle/go/frameworks/Protobuf.qll
> +    if node.getBase() instanceof DataFlow::PointerDereferenceNode
Rewrote to not use `if` in that case

2020-09-04 16:06 UTC, smowton commented
@max-schaefer changes applied, running a distcompare now

2020-09-07 09:45 UTC, smowton commented
Distcompare results are unremarkable; think this is ready to merge.

2020-09-07 10:42 UTC, max-schaefer approved these changes

2020-09-07 10:42 UTC, merged