Promote OAuth2-misuse query to mainline
github/codeql-go pull request #291
Opened 2020-08-18 14:33 UTC by smowton

2020-08-19 20:28 UTC, intrigus-lgtm commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +   * Propagates a URL written to a RedirectURL field to the whole Config object.
```suggestion
   * Holds if `pred` writes a URL to the `RedirectURL` field of the `succ` `Config` object.
```

2020-08-20 10:36 UTC, smowton commented
@intrigus-lgtm thanks, all applied

2020-08-20 23:31 UTC, sauyon commented
Added @shati-patel for doc review.

2020-08-24 16:15 UTC, shati-patel reviewed
Just some minor editorial notes (I can't comment on the `.qhelp` inline):
- Missing word and small typo in the second sentence of the overview: "The Go OAuth 2.0 library allows **you** to specify a "state" value... susceptible to **a** CSRF attack." 
- That sentence also sounds quite long and complicated. Here's a suggestion to make it simpler, but feel free to ignore/edit it as appropriate! (I don't know ~anything~ much about the OAuth libraries 🙈)
  > The Go OAuth 2.0 library allows you to specify a "state" value which is then included in the auth code URL. The remote authentication server then provides the "state" value back in the redirect callback, from where it must be validated. Failure to validate it makes the client susceptible to a CSRF attack.

  (maybe? I wasn't sure what exactly "failure to do so" was referring to)

- Are there any references that you could add?

2020-08-27 13:47 UTC, smowton commented
Help improved, thanks @shati-patel! Will merge once passing CI.

2020-08-27 13:57 UTC, max-schaefer commented
I'm taking a quick look at this, please don't merge yet.

2020-08-27 14:13 UTC, max-schaefer requested changes
Apologies, late to the party, but I have a few suggestions.

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +    exists(Fmt::Printer printer | call = printer.getACall() | sink = call.getArgument(_))
Do we need this? It seems that calls to a `Fmt::Printer` should also be `LoggerCall`s.

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/Bufio.qll
> +     * Returns the node corresponding to the `io.Reader`
```suggestion
     * Gets the node corresponding to the `io.Reader`
```

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/Bufio.qll
> +  class NewScannerCall extends DataFlow::CallNode {
It's generally preferable to model things at the level of functions rather than function calls, so I'd suggest moving the `getReader()` predicate to `NewScanner`, making it something like

```ql
FunctionInput getReader() { result.isParameter(0) }
```

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +    )
It looks to me like this really wants to be `StringOps::Concatenation::taintStep(pred, succ)`, though that doesn't seem to cover all of `Fmt::Sprinter` yet. (It should.)

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +    state.isConst() and source.asExpr() = state and not DataFlow::isReturnedWithError(source)
Why do we need this two-argument version, given that for all intents and purposes `state` is the same as `source`?

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +/** Get a dataflow node that reads the value of `os.Stdin`. */
```suggestion
/** Get a data-flow node that reads the value of `os.Stdin`. */
```

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +  result.(Bufio::NewScannerCall).getReader() = getAStdinNode()
Are we missing a common superclass here?

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +  exists(DataFlow::CallNode call | call = getAScannerCall() | call.getRoot() = funcDef)
```suggestion
  getAScannerCall().getRoot() = funcDef
```

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +  result.(Bufio::NewScannerCall).getReader() = getAStdinNode()
Also, would it be worth using global value numbering here to support cases where `os.Stdin` isn't directly passed as the argument but rather stored in a variable first?

2020-08-27 14:13 UTC, max-schaefer commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +    exists(AuthCodeURL m | call = m.getACall() | source = call.getResult())
This two-parameter version seems unnecessary, considering that `call.getResult() = call`.

2020-09-02 12:51 UTC, smowton commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +    )
Replaced with `TaintTracking::functionModelStep(any(Fmt::Sprinter s), pred, succ)`

2020-09-02 12:54 UTC, smowton commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +    exists(Fmt::Printer printer | call = printer.getACall() | sink = call.getArgument(_))
So it is; I'd assumed LoggerCall intended to capture things that record a persistent log (cf. spitting it out to the terminal, perhaps to be logged, perhaps not)

2020-09-02 13:16 UTC, smowton commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +    state.isConst() and source.asExpr() = state and not DataFlow::isReturnedWithError(source)
I guess it used to be used in the alert message. Removed.

2020-09-02 13:29 UTC, smowton commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +  result.(Bufio::NewScannerCall).getReader() = getAStdinNode()
I dunno, they seem like they don't have a whole lot in common except consuming a stream? One actually reads it, the other constructs a reader with probable later intent to read it... I'm inclined to say the commonality is particular to this caller

2020-09-02 13:29 UTC, smowton commented on ql/src/Security/CWE-352/ConstantOauth2State.ql
> +  result.(Bufio::NewScannerCall).getReader() = getAStdinNode()
GVNs: done

2020-09-02 16:41 UTC, smowton commented
@max-schaefer comments applied

2020-09-04 09:50 UTC, max-schaefer approved these changes

2020-09-04 09:50 UTC, merged