Add workaround for go 1.14 explicit vendoring requirement
github/codeql-go pull request #301
Opened 2020-08-24 07:43 UTC by sauyon

2020-08-24 08:01 UTC, max-schaefer requested changes
Thanks for tackling this so quickly! I have a few minor comments and questions, and this also needs to be tested carefully. I think we should put this into 1.25, since it would be perceived as a regression.

2020-08-24 08:01 UTC, max-schaefer commented on extractor/cli/go-autobuilder/go-autobuilder.go
> +func addVersionToMod(goMod []byte, version string) string {
So, does this function simply insert a line `go <version>` after a `module` directive? If so, wouldn't it be better expressed as a regexp replacement? Something like `moduleRe.ReplaceAll(goMod, "$1\ngo " + version)` where `moduleRe := regexp.MustCompile("(?m)^(module .*)$")`.

2020-08-24 08:02 UTC, sauyon commented on extractor/cli/go-autobuilder/go-autobuilder.go
> +		// hack to fix vendor issues with go versions < 1.14
Right.

2020-08-24 08:15 UTC, sauyon commented
Fix-up'd and pushed the changes.

2020-08-24 08:18 UTC, max-schaefer commented
Thanks, can you retarget this at `rc/1.25`, please?

Then we'll need to do some testing. Perhaps let's start off with a dist-compare, but we also need an LGTM.com distribution upgrade.

2020-08-24 08:26 UTC, sauyon commented
I've retargeted to rc/1.25. I'm not actually able to do dist-compares at the moment because I've left my laptop at my Grandmother's (which is being used as a temporary office). Could you do that?

2020-08-24 08:29 UTC, max-schaefer commented
Sure, will do.

2020-08-24 08:49 UTC, max-schaefer commented on extractor/cli/go-autobuilder/go-autobuilder.go
> +func addVersionToMod(goMod []byte, version string) []byte {
Actually, come to think of it, wouldn't it be safer to call `go mod edit -go=1.13` instead of trying to do this manually?

2020-08-24 09:26 UTC, smowton reviewed
What does this do in the case where vendor/modules.txt is not present?

2020-08-24 11:50 UTC, smowton commented
distcompare for this underway on my Azure VM

2020-08-24 15:59 UTC, sauyon commented on extractor/cli/go-autobuilder/go-autobuilder.go
> +func addVersionToMod(goMod []byte, version string) []byte {
Ah, I hadn't realised this was possible.

2020-08-24 16:01 UTC, sauyon commented
> What does this do in the case where vendor/modules.txt is not present?

I don't believe that there is a version of Go where no modules.txt is generated for vendored dependencies when there is a module file, though I may be mistaken.

2020-08-24 16:05 UTC, sauyon commented
Force-pushed a change to use `go mod edit`.

2020-08-25 08:03 UTC, max-schaefer commented
> @sauyon pushed 70 commits.

Wrong base branch?

2020-08-25 08:05 UTC, sauyon commented
> Wrong base branch?

Oops, muscle memory...

2020-08-27 11:04 UTC, closed without merging