add security rules
github/codeql-go pull request #307
Opened 2020-08-25 05:35 UTC by onkyoworm

hello, i write some security rules of go in ql,
1、CORSChecking
2、CookieAttributesChecking
3、UnSafetySignatureGenerate

2020-08-25 07:00 UTC, max-schaefer requested changes
Many thanks for your contribution!

Could I ask that you move your queries into the `ql/src/experimental` folder (and tests into `ql/test/experimental`)? We generally prefer for new queries to be put there first. They can then be improved step by step, and ultimately may be moved into the default query suite. See https://github.com/github/codeql-go/blob/main/ql/docs/experimental.md for details.

That guide also provides more details about the expected formatting, style, and other aspects. I have pointed out a few places where your contribution needs a bit more work for one of the queries below, similar comments apply to the other queries.

Again, thank you for spending time on putting this pull request together; we look forward to improving it together with you.

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> + * @kind cors
Should be `@kind problem`; see https://github.com/github/codeql/blob/master/docs/query-metadata-style-guide.md.

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            and c.getArgument(0).toString().matches("\"Access-Control-Allow-Origin\"")
We generally discourage the use of `toString()` in queries (cf https://github.com/github/codeql-go/blob/main/ql/docs/experimental.md). In this case, I think you want

```suggestion
            and c.getArgument(0).getStringValue() = "Access-Control-Allow-Origin"
```

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            and c.getArgument(1).toString().matches("\"*\"")
```suggestion
            and c.getArgument(1).getStringValue() = "*"
```

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            and s = "Critical! You set all origin can access,  it could be attakced by CORS"
This alert message doesn't match our usual style. I would suggest you try and rephrase it in a more neutral tone, perhaps something like

```suggestion
            and s = "Allowing access from arbitrary origins may facilitate CORS attacks."
```

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            // and c = f.getACall()
```suggestion
```

We don't normally check in commented-out code.

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            and c.getArgument(1).toString().matches("\"true\"")
```suggestion
            and c.getArgument(0).getStringValue() = "Access-Control-Allow-Credentials" and
            and c.getArgument(1).getStringValue() = "true"
```

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            and s = "Warning! You set send credentials as ture. If your config Access-Control-Allow-Origin unproperly, it could be attakced by CORS"
```suggestion
            and s = "Allowing access to credentials can facilitate CORS attacks if Access-Control-Allow-Origin is configured improperly."
```

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            //c.getArgument(0).toString().matches("\"Access-Control-Allow-Origin\"")
```suggestion
```

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            and c.getArgument(1).toString().regexpMatch("(?i).*?(put|head|delete|options).*?")
```suggestion
            and c.getArgument(0).getStringValue() = "Access-Control-Allow-Methods" and
            and c.getArgument(1).getStringValue().regexpMatch("(?i).*?(put|head|delete|options).*?")
```

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +            and s = "Info! Unexpected http method used, please check it"
```suggestion
            and s = "Allowing HTTP methods such as PUT and DELETE may be dangerous."
```

2020-08-25 07:00 UTC, max-schaefer commented on ql/src/Security/CORSchecking/CORSChecking.ql
> +select "Usage here: ", c, c.asExpr().getLocation(), s
Alert queries should select two things: a program element, and an alert message.

```suggestion
select c, s
```

2020-08-25 10:46 UTC, onkyoworm commented
thanks for your help !, i just fix it and commit again

2020-08-26 06:54 UTC, max-schaefer requested changes
Thanks! A few more comments and suggestions. Also, could you please auto-format your `.ql` files, either in VSCode or by running `make autoformat` from the command line?

2020-08-26 06:54 UTC, max-schaefer commented on ql/test/experimental/UnsafetySignatureGenerate/default.go
> +		hashfucker := sha256.New()
Could you rename this variable, please?

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/CORSchecking/CORSChecking.qhelp
> +<!DOCTYPE qhelp PUBLIC
It's fine for experimental queries not to have a `.qhelp` file, so if you don't quite know yet how to best explain what your query does, you can simply remove the `.qhelp`.

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +/**
This query still uses `toString()` in a few places; could you fix those, please?

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +    f.getName() = "SetCookie"
It seems like you're not actually using this variable for anything.

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +    and s.getType().toString() = "Cookie"
```suggestion
    and s.getType().hasQualifiedName("net/http", "Cookie")
```

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +    and x in [1 .. 20]
Why do you need this?

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +            s.getKey(x).toString() = "HttpOnly"
```suggestion
            s.getKey(x).(Ident).getName() = "HttpOnly"
```

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +            and s.getAnElement().getChild(1).toString() = "false"
```suggestion
            and s.getValue(x).getBoolValue() = false
```

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +        )
```suggestion
        not s.getKey(_).(Ident).getName() = "HttpOnly" and
        infor = "You did not use Cookie attribute HttpOnly"
```

You then don't need `tmp` anymore, and you only need `x` in the first part of the `or`, so you probably want to restrict its scope using an `exists`.

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.qhelp
> +<!DOCTYPE qhelp PUBLIC
I don't understand what this query does.

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +            source.asExpr() = f1.getACall().asExpr()
Why not just `source = f1.getACall()`?

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +            call1.toString().matches(a1.getRhs().toString())
```suggestion
            a1.getRhs() = call1.asExpr()
```

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +            call2.getReceiver().toString() = a1.getLhs().toString()
```suggestion
            exists(Variable x |
              a1.getLhs() = x.getAReference() and
              call1.getReceiver() = x.getARead()
            )
```

However, I think it would be even better to express this using data flow. Then you don't need to reason about `a1` at all: `DataFlow::localFlow(call1, call2.getReceiver())`.

2020-08-26 06:54 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +                b1.getLeftOperand().asExpr().toString() = a1.getLhs().toString() or
Similar to above: use `Variable` or data flow.

2020-08-26 08:08 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.qhelp
> +<!DOCTYPE qhelp PUBLIC
this rule is about the developer use a wrong way to check the signature that come from the user or web end
try to image a sceen like this,
url like this `/check.php?para1=abc&para2=def&sign=xxxxxx`
para1 and para2 is parameter that come from and can controled by users, and sign is the signature of them like sha1(para1+para2) or something others like this
but if the backend(server) ensure the signature easily just by calculate them like sha1(para1+) and compare it with the signature from web, this would be dangerous.

this would be show easily and dangerous in some payment scene，here is an example
you are buying some from ebay, such as 10 books, and each one is 10 dollers, the total count of them is 100 dollers
usually, web end needs send count and each books money to back end, and also a sign of them
just like `/buy.php?count=10&perMoney=10&sign=xxxxx` here sign = sha1(count+perMoney)
if the server calculate it by sha1(count+perMoney) as the web do, it could be bypass easily
because count + perMoney = 1010, if the hacker interrupt the request（burp or something others）, and change count into '1' and perMoney into '010'，no matter the web or ther server would get the same result as count '10' and perMoney into '10'
so the server would beileve that the paramater is correct and use it as usuall, this would do harm to the money or some logic of them

2020-08-26 08:23 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +            source.asExpr() = f1.getACall().asExpr()
haha, i am jsut new to here, not so familiar with it, so sometimes write some rules that could work but so ugly
thanks for your suggestions, i will update it quickly,

2020-08-26 11:10 UTC, onkyoworm commented on ql/test/experimental/UnsafetySignatureGenerate/default.go
> +		hashfucker := sha256.New()
oh sorry i forgot to change it

2020-08-26 11:15 UTC, intrigus-lgtm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.qhelp
> +<!DOCTYPE qhelp PUBLIC
This sounds interesting. Do you have a reference for this type of attack?

2020-08-26 11:21 UTC, onkyoworm commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +/**
after testing, i only found `s.getKey(x).toString = "HttpOnlye"` can be changed into `s.getKey(x).getStringValue() = "HttpOnly"`
but other could not, if you can please tell me

2020-08-26 11:43 UTC, onkyoworm commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +    f.getName() = "SetCookie"
which one？ do you mean  x? infor?or tmp?
here is an explanation:
x :  i found there is so many attributes in cookie, but you can't locate the "httponly" attributes by an extractly index，so i use a loop in [1 .. 20] to get the attributes call "httponly"
infor : this is easy, the information that i want to give to users
tmp: this is a liite complex to explain, i use "concat" to combine all of the attributes into a string, so i could check if the developer set "httponly" attributes or not

2020-08-26 11:46 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.qhelp
> +<!DOCTYPE qhelp PUBLIC
yeah, we have some real case of this type of attack (but in chinese),
but i don't the exactly name of this type of attack in english,
so i am spending times on finding the same of this type of attack in english

2020-08-26 15:05 UTC, smowton commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.qhelp
> +<!DOCTYPE qhelp PUBLIC
Can't find a better reference than https://crypto.stackexchange.com/questions/55162/best-way-to-hash-two-values-into-one at the moment

2020-08-27 05:42 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.qhelp
> +<!DOCTYPE qhelp PUBLIC
@smowton  can't agree any more

2020-08-27 05:45 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +            f2.hasQualifiedName("crypto/sha256", "New")
yes, but in most code, i found they use sha256. Later could expand the range of the hash algorithms

2020-08-27 05:48 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +                f1.hasQualifiedName("github.com/astaxie/beego.Controller", "GetInt") or
Good idea, but i have no idea that UntrustedFlowSource whether include this sources of framework "beego", so i just specify the sources by myself,
Later i would rewrite it with UntrustedFlowSource and test it

2020-08-27 05:59 UTC, onkyoworm commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +            and s = "Allowing access to credentials can facilitate CORS attacks if Access-Control-Allow-Origin is configured improperly."
what about this
`Allowing Access-Control-Allow-Credentials as true would expand you attack surface if CORS attacks appears`

2020-08-27 08:07 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +    f.getName() = "SetCookie"
The variable `f`, which seems to be the only variable mentioned on this line. You are not using it for anything, so you might as well drop it.

2020-08-27 08:08 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +/**
I'm sorry, I don't understand what you are trying to say.

2020-08-27 08:10 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +    f.getName() = "SetCookie"
> x : i found there is so many attributes in cookie, but you can't locate the "httponly" attributes by an extractly index，so i use a loop in [1 .. 20] to get the attributes call "httponly"

There are no loops in CodeQL. When you say `s.getKey(x)` below, then that is enough to assign a value to `x`; you don't need to constrain it further, so you can just drop the `x in [1..20]` bit. (As mentioned below, you'll then also want to restrict the scope of `x` to the first part of the `or` by using an `exists`.)

2020-08-27 08:12 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +            and s.getAnElement().getChild(1).toString() = "false"
I think this is a better idea than what I suggested above.

2020-08-27 08:13 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +            f2.hasQualifiedName("crypto/sha256", "New")
Agreed; no need to do the generalisation for the initial experimental query.

2020-08-27 08:13 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +                f1.hasQualifiedName("github.com/astaxie/beego.Controller", "GetInt") or
We do not have a built-in model for `beego` at the moment. Leaving this as-is and generalising later is probably fine.

2020-09-01 07:24 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +/**
Resolved in off-line discussion.

2020-09-01 07:32 UTC, max-schaefer requested changes
Thank you for working with us on improving this query. I have a few more suggestions. Also, you will need to autoformat everything in order to pass our continuous integration tests.

2020-09-01 07:32 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +        tmp.matches("%HttpOnly%")
No need for this level of trickery. You can simply do

```suggestion
        not exists(KeyValueExpr k2 |
          k2 = s.getAnElement() and
          k2..getKey(i).(Ident).getName() = "HttpOnly"
        )
```

and get rid of `tmp`.

2020-09-01 07:32 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +            DataFlow::localFlow(call1, call2.getReceiver())
Now that you are using `localFlow` you don't need `a1` above any more.

2020-09-01 07:32 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +            call2.getCalleeName() = "Write"
It doesn't look like `call2` is used in the definition of `source`. Should it perhaps be used in some way?

2020-09-01 07:32 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +                DataFlow::localFlow(call1, b1.getLeftOperand())
As above, using `localFlow` means you don't need to reason about the assignment `a1` any more, I think you can just remove it.

2020-09-01 07:32 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +* @name Unsafety Signature Generate checking
Slightly awkward name; perhaps change to something like

```suggestion
* @name Unsafe signature calculation
```

2020-09-01 08:09 UTC, onkyoworm commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +        tmp.matches("%HttpOnly%")
awesome！ i try many times using exists or any or for，but i could not fix this problem，so i have to use the tmp

2020-09-01 08:10 UTC, onkyoworm commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +        tmp.matches("%HttpOnly%")
to autoformat the ql file, using `codeql query format file`?

2020-09-01 08:22 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +        tmp.matches("%HttpOnly%")
That's right, yes.

2020-09-01 08:23 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +        tmp.matches("%HttpOnly%")
(And don't forget to pass `-i` to make it update the file in place.)

2020-09-07 10:49 UTC, max-schaefer requested changes
Some more questions about the third query; also, the formatting still doesn't seem to be right.

2020-09-07 10:49 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      c1.getCalleeName() = "Write" and
What is the role of `c1`? It does not seem to have anything to do with `source`.

2020-09-07 10:49 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      source = d.getASuccessor()
Why `getASuccessor()`?

2020-09-07 10:49 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +  override predicate isSink(DataFlow::Node sink) {
Can you briefly explain what this predicate is meant to do? It seems to repeat parts of `isSource` which doesn't look right.

2020-09-07 12:49 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +  override predicate isSink(DataFlow::Node sink) {
yeah, now i am curious about where should i define the source and the sink
and i think there is server kinds of situations
1、source：where the frame get user input， like function `GetString` in beego
 sink：where the developer compare the result with his calced result and sign from the web. like `$calced_value == $SignFromWeb`

2、source：the result of the developer calced
sink：where the developer compare the result with his calced result and sign from the web. like `$calced_value == $SignFromWeb`

which one would be better？ @max-schaefer

2020-09-07 15:00 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +  override predicate isSink(DataFlow::Node sink) {
I think it should be 1., if I understand correctly.

2020-09-17 08:29 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      c1.getCalleeName() = "Write" and
Interesting! i deleted c1 and found it work as usual
At first, i use c1 to ensure the code did something to calc the hash, like
`hashCalc := sha256.New()`
`hashCalc.Write(message_2)`
In Go, you must declare it, and then use it's `Write` method

but by just deleting the line23 , i found it work as usual,
thanks

2020-09-17 08:46 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      source = d.getASuccessor()
yeah, this is something different between using `d` and `d.getASuccessor()`
here is the result of using `d`
you would found there is two kind of result `call to xxx` and the varialbe using `Getxxx` of beego to get user input
In this way, you would found the hole life circle of the variable, but i think this is a lttile complex
because in some situation like having so many filter function with the user's input
you would find so many result with the query
and what i want is to focus the first entrance  of it , and i found `getASuccessor()` work, so i use it
and the result is like the second photo
(if necessary, i could change it into just using `d`)
![image](https://user-images.githubusercontent.com/16128133/93444715-4f5e0000-f903-11ea-9f0c-0b320c5f16f6.png)


![image](https://user-images.githubusercontent.com/16128133/93446520-e4f98f80-f903-11ea-8328-430c39a46931.png)

2020-09-18 07:42 UTC, max-schaefer requested changes

2020-09-18 07:42 UTC, max-schaefer commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +  )
I think you probably want to move this brace down to line 24. Otherwise lines 20-24 apply to _any_ struct literal `s`, not just `Cookie` structs.

2020-09-18 07:42 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      c1.getCalleeName() = "Write" and
So are you planning on deleting this line?

2020-09-18 07:42 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      source = d.getASuccessor()
I'm not entirely sure I understand, but are you saying that you think there will be too many sources if you omit the `getASuccessor`? Have you observed this to actually be a problem?

I think it might be easiest to just define `source = m.getACall()` and omit `d` entirely. The global data-flow will follow any steps that `localFlow` follows anyway.

2020-09-18 07:42 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +  override predicate isSink(DataFlow::Node sink) {
Did you want to try and implement 1.?

2020-09-18 07:42 UTC, max-schaefer commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "Allowing Access-Control-Allow-Credentials as true would expand you attack surface if CORS attacks appears。"
```suggestion
      "Allowing Access-Control-Allow-Credentials as true would expand you attack surface if CORS attacks appears."
```

2020-09-22 14:46 UTC, onkyoworm commented on ql/src/experimental/CookieAttributesChecking/CookieAttributesChecking.ql
> +  )
good idea, i will fix it
besides, i have add something news in the demo code of go for testing `any struct literal s` that you say

2020-09-22 14:47 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +  override predicate isSink(DataFlow::Node sink) {
yes, i try 1 and later i would update it

2020-09-22 14:51 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      source = d.getASuccessor()
sounds great, let me try

2020-09-22 15:02 UTC, onkyoworm commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      c1.getCalleeName() = "Write" and
i am not sure it's suitable or not to delete this line, because during my test (with code i have been saw and i thought out), it still works if i delete it.
i have no idea it would work well or not if you delete it in others situation,.
but in seriously, i think it should not be deleted if you want it run in critial

2020-09-22 15:08 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafetySignatureGenerate.ql
> +      c1.getCalleeName() = "Write" and
I'm not sure what you mean. This line is almost useless. The only thing it does is to ensure that there is a call to `Write` somewhere in the program. However, that call is not required to be related to `source` in any way at all. That doesn't sound like a very useful thing to check.

2020-10-09 08:23 UTC, max-schaefer requested changes
A few more suggestions. I also noticed that you haven't checked in the `.qlref` and `.expected` files for your tests, so at the moment no tests are being run.

2020-10-09 08:23 UTC, max-schaefer commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "Allowing Access-Control-Allow-Credentials as true would expand you attack surface if CORS attacks appears。"
The period at the end of the message still needs to be fixed. I have also suggested a rewrite of the text to make the grammar a bit smoother.

2020-10-09 08:23 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafeSignatureGenerate.ql
> +import go
This query lacks metadata (`@name`, `@description`, etc.).

2020-10-09 08:23 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafeSignatureGenerate.ql
> +  b.getOperator() = "==" and
You could also change the type of `b` to `DataFlow::EqualityTestNode`.

2020-10-09 08:23 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafeSignatureGenerate.ql
> +    b.getAnOperand().toString() = a.getAnLhs().toString()
As before, I think it would be nicer to phrase this in terms of data flow:

```ql
DataFlow::localFlow(m.getACall(), b.getAnOperand()) and
DataFlow::localFlow(c1, b.getAnOperand())
```

2020-10-09 08:23 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafeSignatureGenerate.ql
> +    b.getAnOperand().toString() = a.getAnLhs().toString()
Also, I would suggest storing `m.getACall()` in a variable `c` so you can reference it in the `select` clause (see below).

2020-10-09 08:23 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafeSignatureGenerate.ql
> +select "Get input here: ", m.getACall(), "Get hash algorithm result here: ", c1,
This `select` doesn't have the right shape for an alert query. You can rewrite it like this:

```ql
select b, "Comparison between $@ and $@.", c, "user input", c1, "hash result"
```

Note that I am assuming here that you have a variable `c` that is bound to the value of `m.getACall()` used above. It is very important to introduce a new variable for this. If you use `m.getACall()` twice, then the two uses may refer to different calls to `m`.

2020-10-09 08:23 UTC, max-schaefer commented on ql/test/experimental/UnsafetySignatureGenerate/default.go
> +	if a == "" && b = "" {
```suggestion
	if a == "" && b == "" {
```

2020-10-16 10:05 UTC, MusaBack approved these changes

2020-10-16 11:05 UTC, MusaBack approved these changes

2020-10-21 18:57 UTC, max-schaefer requested changes
One more thing I just noticed: none of your new queries have an `@id`. Could you add them? Also, were you planning on adding/enabling tests?

2020-10-21 18:57 UTC, max-schaefer commented on ql/src/experimental/UnsafetySignatureGenerate/UnSafeSignatureGenerate.ql
>    b.getOperator() = "==" and
This check is no longer needed now that `b` has type `DataFlow::EqualityTestNode`.

2020-10-21 18:57 UTC, max-schaefer commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
```suggestion
      "Setting \"Access-Control-Allow-Credentials\" to \"true\" may facilitate CORS attacks."
```

2020-10-22 01:48 UTC, onkyoworm commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
Thanks schaefer, i have fixed what you suggestion, but i still have i question: i am using mac, but i found it always failed in Step: Test Linux (Ubuntu) when i commit
Should i build an Ubuntu enviroment and test the code in it before i commit?
For example, `test -z "$(git ls-files | grep '\.go$' | grep -v ^vendor/ | xargs grep -L "//\s*autoformat-ignore" | xargs gofmt -l)"` this commang show no errors in mac,  but in codeql test, it shows errors

2020-10-22 07:57 UTC, max-schaefer commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
There are a few platform-independent checks, which are run as part of the "Test Linux (Ubuntu)" step, but not as part of the other steps. This test failure in particular means that you need to autoformat your `.go` files; you can use `make autoformat` to do that.

2020-10-22 08:45 UTC, onkyoworm commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
thanks, i would reformat the .go file
Besides, what do you mean `adding/enabling tests`? i have added the demo code with go in `ql/test/experimental` do i need to add another testing?

2020-10-22 08:48 UTC, max-schaefer commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
Yes, you need to add a `.qlref` file referring to the query next to it. See [here](https://github.com/github/codeql-go/blob/main/ql/test/experimental/CWE-327/InsecureRandomness.qlref) for an example of how that is done. Then you use `codeql test run` to run the tests as explained [here](https://help.semmle.com/codeql/codeql-cli/procedures/test-queries.html#running-codeql-test-run).

2020-10-22 11:55 UTC, onkyoworm commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
[here](https://help.semmle.com/codeql/codeql-cli/procedures/test-queries.html) told me when `0 tests passed; 1 tests failed:` appear means i should add a `.expected` file. And i found some  expected file [here](https://github.com/github/codeql-go/blob/main/ql/test/experimental/CWE-327/WeakCryptoAlgorithm.expected) but after reading it, i am confuse about how to get it?
here is my command result

x@x codeql-go % ~/code-audit/codeql-cli/codeql/codeql test run --search-path=ql ql/test/experimental/UnsafetySignatureGenerate
Executing 1 tests in 1 directories.
Extracting test database in /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate.
Upgrading database for /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate.
Could not upgrade the dataset in /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate: Unrecoverable mismatch between extractor and library dbschemes.
Extractor produced: (bcbec1b0e44ae4365dd4e5bade5aec80135a4a00) /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate/UnsafetySignatureGenerate.testproj/db-go/go.dbscheme
We can upgrade to: (bcbec1b0e44ae4365dd4e5bade5aec80135a4a00) /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate/UnsafetySignatureGenerate.testproj/db-go/go.dbscheme
The query expects: (4affa49dbe2bbab1a33f0e3ea6b045116abbcfda) /Users/choohan/forgit/mygit/codeql-go/ql/src/go.dbscheme
Unrecoverable mismatch between extractor and library dbschemes.
Extractor produced: (bcbec1b0e44ae4365dd4e5bade5aec80135a4a00) /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate/UnsafetySignatureGenerate.testproj/db-go/go.dbscheme
We can upgrade to: (bcbec1b0e44ae4365dd4e5bade5aec80135a4a00) /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate/UnsafetySignatureGenerate.testproj/db-go/go.dbscheme
The query expects: (4affa49dbe2bbab1a33f0e3ea6b045116abbcfda) /Users/choohan/forgit/mygit/codeql-go/ql/src/go.dbscheme
[1/1] FAILED(UPGRADE) /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate/UnsafetySignatureGenerate.qlref
0 tests passed; 1 tests failed:
  FAILED: /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate/UnsafetySignatureGenerate.qlref

2020-10-22 13:20 UTC, max-schaefer commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
You need to solve another problem first: I think your installation of CodeQL is too old, leading to the

> Unrecoverable mismatch between extractor and library dbschemes.

the test runner is complaining about. So you first need to upgrade to a never version of CodeQL. Alternatively, make sure that your `--search-path` refers to your check-out of the codeql-go repository (not the codeql repository).

Then, you can use `codeql test run --learn` to produce a `.expected` file.

2020-10-23 09:14 UTC, onkyoworm commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
Excellent！after updating codeql, codeql-go and codeql-cli i resolved it and generate `.expected` file successfully.
But in case `UnsafetySignatureGenerate`, use `codeql test run --learn` could pass the test, but nothing  in `.expected` file
is it right? ( others case have result in `.expected` file)
command result here:

x@x codeql-go % ~/code-audit/codeql-cli/codeql/codeql test run --learn --search-path=ql ql/test/experimental/UnsafetySignatureGenerate
Executing 1 tests in 1 directories.
Extracting test database in /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate.
Compiling queries in /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate.
Executing tests in /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate.
[1/1 eval 956ms] PASSED /Users/choohan/forgit/mygit/codeql-go/ql/test/experimental/UnsafetySignatureGenerate/UnsafetySignatureGenerate.qlref
All 1 tests passed.

2020-10-23 09:48 UTC, max-schaefer commented on ql/src/experimental/CORSchecking/CORSChecking.ql
> +      "If \"Access-Control-Allow-Credentials\" is set as \"TURE\", you are easier to be attacked when CORS attacks happen."
> But in case UnsafetySignatureGenerate, use codeql test run --learn could pass the test, but nothing in .expected file
is it right?

That means the query produced no results on your test file, which is probably not what you want, and most likely means there is a mistake in your query or in the test file.

2021-09-14 16:39 UTC, smowton commented
Closing because inactive; feel free to reopen if you want or revisit this

2021-09-14 16:39 UTC, closed without merging