Add taint-tracking for `reflect` package
github/codeql-go pull request #317
Opened 2020-09-01 11:28 UTC by gagliardetto

This PR adds taint-tracking classes for the `reflect` package.

---

`codebox` command:

```bash
codebox --out-dir=./generated/latest --pkg=/usr/local/go/src/reflect --http
```

2020-09-02 11:19 UTC, smowton commented
Same note as on the other PR -- lots of tests added, but no expectations?

2020-09-02 11:35 UTC, gagliardetto commented
As suggested by @max-schaefer a few months ago, the tests' .expected file tracks **missed** flows only. If there's something added to the .expected file, it means something does **not** flow where it should.

2020-09-02 11:47 UTC, gagliardetto commented
Here's the original comment https://github.com/github/codeql-go/pull/251#discussion_r452891514

2020-09-04 09:56 UTC, max-schaefer requested changes
Basically LGTM, though I think there are some methods that we perhaps can drop. Out of interest, are you aware of an example of an attack that involves this package?

2020-09-04 09:56 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/Reflect.qll
> +      (inp.isReceiver() and outp.isResult())
While it's technically true that the output is tainted by the receiver in this case, we generally ignore taint flow through Booleans and numbers, since they provide very little leverage for a would-be attacker.

2020-09-04 09:56 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/Reflect.qll
> +      (inp.isReceiver() and outp.isResult())
(This remark also applies to the various number-typed methods below.)

2020-09-04 10:11 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/stdlib/Reflect.qll
> +      (inp.isReceiver() and outp.isResult())
Absolutely.

I think the uintptr-related ones should be kept, though.

2020-09-04 10:41 UTC, gagliardetto commented
> Out of interest, are you aware of an example of an attack that involves this package?

No, not directly.

2020-09-07 09:47 UTC, smowton commented
Running a distcompare and lgtm test for this now

2020-09-07 12:38 UTC, gagliardetto commented
Awesome! Thank you @smowton

2020-09-08 11:36 UTC, smowton commented
I ran joint tests of this, #318, #320, #321, #322 and #323 through lgtm.com's full Go suite, using the reflected XSS query. Findings, part 1:

New true positives:
* 2 projects due to HTML templating
* 3 projects due to extracting a JSON field and echoing it unescaped
* 1 project due to multipart document extraction
* 1 project due to form field extraction
* 1 project due to base64 decoding of an HTTP header

New false positives:
* 2 projects due to query string extraction, but subsequent JSON encoding
* 1 project due to hex-encoding a user-provided string, which makes it safe for XSS purposes
* 1 project due to reflected XML (the content-type was also copied, so we didn't notice the incoming user-supplied XML was being given a non-html content-type)

2020-09-08 13:11 UTC, smowton commented
Nothing remarkable found in the other half of my testing query. To sum up, we should note that encoding something in base64, hex and so on neutralises most attacks, and double-check out detection of JSON encoding.

2020-09-08 13:59 UTC, max-schaefer commented
Wow, that's quite a crop!

> encoding something in base64, hex and so on neutralises most attacks

Yes, I would advocate not treating encoding functions like that as general-purpose taint steps. Queries that are particularly interested in those steps should add them explicitly.

2020-09-09 07:25 UTC, gagliardetto commented
> I ran joint tests of this, #318, #320, #321, #322 and #323 through lgtm.com's full Go suite, using the reflected XSS query. Findings, part 1:
> 
> New true positives:
> 
> * 2 projects due to HTML templating
> * 3 projects due to extracting a JSON field and echoing it unescaped
> * 1 project due to multipart document extraction
> * 1 project due to form field extraction
> * 1 project due to base64 decoding of an HTTP header
> 
> New false positives:
> 
> * 2 projects due to query string extraction, but subsequent JSON encoding
> * 1 project due to hex-encoding a user-provided string, which makes it safe for XSS purposes
> * 1 project due to reflected XML (the content-type was also copied, so we didn't notice the incoming user-supplied XML was being given a non-html content-type)

Thanks! That's something!

2020-09-10 11:09 UTC, smowton commented
Finished a dist-compare for this group of PRs. Performance results are fine. Result changes:

* 2 new FPs due to String.split being used to split the username and password of an HTTP Authorization header
* 12 new (probable) FPs due to detecting spurious path-injection problems. I think the flow is correct, the problem is spotting the particular way they're making sure a user-supplied path falls within their working directory.
* 3 new FPs due to suspected URL injection, when in fact the allowed URLs are tightly constrained
* 1 new FP due to suspected SQL injection when that SQL is properly escaped.

I will look at improving our sanitisers for these now.

2020-09-10 15:23 UTC, smowton commented
Here's a sanitiser for the HTTP Authorization header: https://github.com/smowton/codeql-go/commit/f6194b52f0bcbe86002341d29fcf1611ca79c99e

The path-injection problems appear to be true positives, as do some of the URL injection and SQL injection issues detected.

There's one URL injection problem that is well sanitised, but I couldn't write a query to detect: each URL element is individually sanity-checked (Host must match this regex... path must be empty... query string can only contain a fixed list of variables), so there's a series of operations that partially sanitise but no definitive point to mark the whole thing as kosher. I think that one regrettably has to be let through, but broadly speaking this is a good haul of results!

2020-09-11 10:18 UTC, smowton approved these changes
I think this package is uncontroversial, suggest to merge @max-schaefer

2020-09-11 10:22 UTC, gagliardetto commented
> which I recommend tacking onto the end of the PR introducing strings.Split*

Can you please review and add that piece? (That's possible, right?)

2020-09-11 10:23 UTC, smowton commented
I can make a derived PR -- I'll do that shortly

2020-09-11 10:25 UTC, gagliardetto commented
Thanks! ☺️

2020-09-11 10:26 UTC, max-schaefer approved these changes

2020-09-11 10:26 UTC, merged