Add taint-tracking for packages in `html/*`
github/codeql-go pull request #322
Opened 2020-09-06 15:58 UTC by gagliardetto

`codebox` commands:

```bash
codebox --out-dir=./generated/latest --pkg=/usr/local/go/src/html --http
codebox --out-dir=./generated/latest --pkg=/usr/local/go/src/html/template --http
```

2020-09-11 10:51 UTC, smowton approved these changes
LGTM

2020-09-14 08:32 UTC, max-schaefer requested changes
Basically LGTM modulo minor comments; also needs conflict resolution.

2020-09-14 08:32 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/Html.qll
> +    string kind;
I don't think we need this field; its value is a known constant.

2020-09-14 08:32 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/HtmlTemplate.qll
> +      (inp.isParameter(0) and outp.isResult())
This should probably have a corresponding subclass of `EscapeFunction::Range`.

More generally, our current modeling of escape functions needs to be improved to allow escape functions whose output isn't the function result (like `HTMLEscape` above), but that doesn't need to happen as part of this PR.

2020-09-14 08:32 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/HtmlTemplate.qll
> +      (inp.isParameter(0) and outp.isResult())
Same as above.

2020-09-14 13:41 UTC, smowton commented
Merged #323 which of course introduces a conflict here -- @gagliardetto please rebase, @max-schaefer I think this should be ok now?

2020-09-15 16:54 UTC, max-schaefer approved these changes

2020-09-15 16:54 UTC, merged