Blejd
github/codeql-go pull request #324
Opened 2020-09-07 07:21 UTC by sauyon

2020-09-07 07:50 UTC, max-schaefer requested changes
Thank you very much for persisting with this! It's pleasantly simple, I only have a couple of fairly minor questions and suggestions.

2020-09-07 07:50 UTC, max-schaefer commented on codeql-tools/autobuild.cmd
> +  type NUL && "%CODEQL_EXTRACTOR_GO_ROOT%/tools/%CODEQL_PLATFORM%/go-build"
No `.exe`?

2020-09-07 07:50 UTC, max-schaefer commented on Makefile
> +BINARIES = go-extractor go-tokenizer go-autobuilder go-build go-bootstrap go-gen-dbscheme
Hm, perhaps `go-build` is slightly confusing, given the similarity to `go build`. How about `go-build-runner`? (It's also more similar to `go-extractor`, `go-autobuilder`, etc.)

2020-09-07 07:50 UTC, max-schaefer commented on change-notes/2020-06-11-build-tracing.md
> +* The extractor can now be used for build tracing, allowing users to supply a build command when creating databases with the CodeQL CLI or via configuration. It currently only supports projects that
This should mention that build tracing is opt-in, but we can add that once we have decided the exact details of how the opting-in works.

2020-09-07 07:50 UTC, max-schaefer commented on extractor/autobuilder/autobuilder.go
> +package autobuilder
I think this could do with a doc comment.

2020-09-07 07:50 UTC, max-schaefer commented on extractor/autobuilder/autobuilder.go
> +var CheckExtracted = false
Again, doc comment would be nice.

2020-09-07 07:50 UTC, max-schaefer commented on extractor/autobuilder/autobuilder.go
> +var CheckExtracted = false
And similarly below.

2020-09-07 07:50 UTC, max-schaefer commented on extractor/autobuilder/autobuilder.go
> +		log.Fatalf("No source directory set.")
Is that an accurate description of the problem? It seems like we shouldn't even be able to get here under normal circumstances, should we?

2020-09-07 07:50 UTC, max-schaefer commented on extractor/autobuilder/autobuilder.go
> +	return false
So this always returns `false`?

2020-09-07 07:50 UTC, max-schaefer commented on extractor/autobuilder/autobuilder.go
> +	// if there is a build file, run the corresponding build tool
This sounds like it wants to be a doc comment.

2020-09-07 07:50 UTC, max-schaefer commented on extractor/autobuilder/autobuilder.go
> +		tryBuild("go", "build", "./...")
So we now always do `go build ./...`? Even when running without build tracing?

2020-09-07 07:50 UTC, max-schaefer commented on extractor/cli/go-build/go-build.go
> +	// we cannot simply call `go build` here, because the tracer is not able to trace calls made by
Always? Or only if it is statically linked? Perhaps it would be safer to explicitly tell the tracer not to trace this binary so we don't get subtly different behaviour on different configurations?

2020-09-07 07:50 UTC, max-schaefer commented on extractor/cli/go-build/go-build.go
> +		log.Fatalf("Could not determine path of autobuilder: %v.\n", err)
```suggestion
		log.Fatalf("Could not determine path of extractor: %v.\n", err)
```

2020-09-07 11:06 UTC, smowton approved these changes
Looks like all my comments apply to commits that are later improved (consider squashing)

2020-09-07 11:06 UTC, smowton commented on extractor/cli/go-extractor/go-extractor.go
> +				if i+1 < len(args) {
Except this one looks real

2020-09-10 07:48 UTC, sauyon commented on extractor/autobuilder/autobuilder.go
> +		log.Fatalf("No source directory set.")
I believe this shouldn't be possible, since this should be caught by `codeql`.

2020-09-10 07:48 UTC, sauyon commented on extractor/autobuilder/autobuilder.go
> +	return false
Urk, I'd accidentally reset away some of my changes while running a compare...

2020-09-10 07:49 UTC, sauyon commented on extractor/cli/go-build/go-build.go
> +	// we cannot simply call `go build` here, because the tracer is not able to trace calls made by
I'm not sure what you mean, but we should probably tell the tracer not to trace the extractor if it doesn't do that by default.

2020-09-10 08:00 UTC, max-schaefer commented on extractor/cli/go-build/go-build.go
> +	// we cannot simply call `go build` here, because the tracer is not able to trace calls made by
Sorry, that wasn't very clear. I was wondering about your comment that "the tracer is not able to trace calls made by this binary". Why is that? Is it never going to be able to trace this binary, or only under certain circumstances?

In any case I think it's safest to explicitly exclude binaries from tracing that we don't want to be traced, even if for some of them we might not normally get tracing for other reasons.

2020-09-10 08:17 UTC, sauyon commented on extractor/cli/go-build/go-build.go
> +	// we cannot simply call `go build` here, because the tracer is not able to trace calls made by
I think it's not possible for it to trace calls made directly by Go binaries on Linux, but it is able to trace calls made by programs called from it. That is, calling `go build` doesn't work, because the tracer wouldn't be able to see that call, but calling `make`, which then calls `go build` is fine.

I've simply replaced what would normally have been a `go build ./...` with `go-extractor ./...` here.

2020-09-10 09:35 UTC, max-schaefer commented on codeql-tools/autobuild.cmd
> +if %CODEQL_GO_TRACE% = "" (
```suggestion
if %CODEQL_EXTRACTOR_GO_TRACE% = "" (
  echo "Tracing enabled"
```

2020-09-10 09:46 UTC, sauyon commented
I've applied all the relevant changes and tried to squash to a sensible history.

Performance evaluation was *very* wobbly. I'm trying again, but may have to throw out the idea of performance testing.

I should probably test on Windows again, all things considered...

2020-09-10 12:58 UTC, max-schaefer commented on extractor/autobuilder/autobuilder.go
> +		log.Fatalf("No source directory set.")
OK, could you reformulate the error message to clarify that this is an unexpected event and there isn't anything a user could do to fix it? (The current message makes it sound like there is.)

2020-09-22 14:13 UTC, max-schaefer commented
As discussed elsewhere, could we rename the environment variable for turning on build tracing from `CODEQL_EXTRACTOR_GO_TRACE` to `CODEQL_EXTRACTOR_GO_BUILD_TRACING` for clarity?

2020-10-14 15:46 UTC, sauyon commented
The experiments I ran did nothing to improve the Kubernetes situation, so I think merging this now is a sensible thing to do.

2020-10-14 16:13 UTC, smowton commented on change-notes/2020-06-11-build-tracing.md
> +* The extractor can now be used for build tracing, allowing users to supply a build command when creating databases with the CodeQL CLI or via configuration. It currently only supports projects that
@sauyon noting this is still to do. Do we have a firm answer on how a user would opt in?

2020-10-14 16:18 UTC, smowton commented on extractor/autobuilder/autobuilder.go
> +		log.Fatalf("No source directory set.")
@sauyon still to-do

2020-10-14 16:22 UTC, smowton reviewed
Highlighted some of Max's outstanding comments, plus one of mine noted below, otherwise as you say let's get this merged. Could you write an issue brain-dumping what you know of the Kubernetes situation?

2020-10-14 16:22 UTC, smowton commented on extractor/cli/go-extractor/go-extractor.go
> +					log.Fatalf("Invalid --mimic: no compiler specified")
```suggestion
					log.Fatalf("--mimic requires an argument, e.g. --mimic go")
```

2020-10-14 16:35 UTC, sauyon commented on change-notes/2020-06-11-build-tracing.md
> +* The extractor can now be used for build tracing, allowing users to supply a build command when creating databases with the CodeQL CLI or via configuration. It currently only supports projects that
I believe that that was likely just the discussion of variable naming.

2020-10-14 16:41 UTC, smowton commented on change-notes/2020-06-11-build-tracing.md
> +* The extractor can now be used for build tracing, allowing users to supply a build command when creating databases with the CodeQL CLI or via configuration. It currently only supports projects that
Cool, in that case mention how it's done in the change-note

2020-10-14 16:46 UTC, sauyon commented
I believe I have now actually addressed all comments.

2020-10-15 09:48 UTC, smowton approved these changes
Nice, looks good! @max-schaefer are you happy to drop your block on this?

2020-10-15 10:26 UTC, max-schaefer approved these changes

2020-10-15 10:26 UTC, max-schaefer commented
Yep, let's give this a try!

2020-10-15 10:27 UTC, smowton commented
@sauyon please link the issue here when you've got a writeup

2020-10-15 10:27 UTC, merged