@gagliardetto Add taint-tracking for package `net`
github/codeql-go pull request #337
Opened 2020-09-12 11:10 UTC by gagliardetto

2020-09-14 09:36 UTC, smowton commented
Will run another batch of comparsions for #331 #332 #333 #334 #335 #336 #337

2020-09-14 11:13 UTC, gagliardetto commented
That's exciting news! Thanks!

2020-09-14 17:02 UTC, smowton commented
Partial results:

New true positives (I think): 5
New false positives: 4

The only FP attributable directly to this PR is regarding the results of ParseIP as dangerous. It's clearly dangerous to parse a user IP and then open a socket to it, for example, but it's not dangerous in most contexts (XSS, SQLi and so on), so I recommend functions like that which tightly constrain the possible form of the input string should not be modelled by default. A query looking for particular circumstances where a user-controlled IP or MAC address or similar *is* dangerous can re-include them.

2020-09-15 11:04 UTC, smowton commented
Performance comparison results are unremarkable. New hits from that run:

1x new allocation-size-overflow -- a marginal case (we're complaining about len(usersupplied) + 8 possibly overflowing), but this PR's contribution is in propagating taint across a regexreplaceall, which is correct.

1x new clear-text logging -- a false positive due to a bearer token that the service parses into a non-secret and a secret component, logging the non-secret. Probably too app-specific to fix.

1x new path injection -- allows an attacker to explore the FS by stat'ing any file they wish, without apparent escaping. Could be an FP if the server uses an OS-level mechanism to limit file accesses.

1x new request-forgery -- an open HTTP proxy

2020-09-15 12:03 UTC, gagliardetto commented
Thanks @smowton and @max-schaefer for all your effort and help in bringing this project to life!

I'll go ahead and submit the last 7 new PRs that will complete the standard library taint-tracking. Or I could wait for next week, but I have time today.

2020-09-16 10:36 UTC, smowton requested changes

2020-09-16 10:36 UTC, smowton commented on ql/src/semmle/go/frameworks/stdlib/Net.qll
> +      hasQualifiedName("net", "ParseCIDR") and
We shouldn't generally consider a string conforming to this format as dangerous

2020-09-16 10:36 UTC, smowton commented on ql/src/semmle/go/frameworks/stdlib/Net.qll
> +      hasQualifiedName("net", "ParseIP") and
Same

2020-09-16 10:36 UTC, smowton commented on ql/src/semmle/go/frameworks/stdlib/Net.qll
> +      hasQualifiedName("net", "ParseMAC") and
Same

2020-09-16 10:36 UTC, smowton commented on ql/src/semmle/go/frameworks/stdlib/Net.qll
> +      this.hasQualifiedName("net", "IP", "UnmarshalText") and
Not generally dangerous (we can keep the rules that propagate within the IP type though -- if some query decides that it *does* care about user-controlled IPs, then it's right to follow that across To4, To16 etc)

2020-09-16 10:37 UTC, smowton commented
Once this is resolved and the `os` package PR is passing tests, then suggest making a big PR that combines all this second tranche (everything up to #337), so we can merge them en masse without repeatedly resolving conflicts on `Stdlib.qll`.

2020-09-20 12:57 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/stdlib/Net.qll
> +      hasQualifiedName("net", "ParseCIDR") and
Removed.

2020-09-20 12:58 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/stdlib/Net.qll
> +      hasQualifiedName("net", "ParseIP") and
Removed.

2020-09-20 12:58 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/stdlib/Net.qll
> +      hasQualifiedName("net", "ParseMAC") and
Removed.

2020-09-20 13:00 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/stdlib/Net.qll
> +      this.hasQualifiedName("net", "IP", "UnmarshalText") and
Removed.

2020-09-21 08:28 UTC, smowton approved these changes

2020-09-21 08:34 UTC, merged