Move to stdlib and extend the models for `fmt` package
github/codeql-go pull request #341
Opened 2020-09-15 16:05 UTC by gagliardetto

`codebox` command:

```bash
codebox --out-dir=./generated/latest --pkg=/usr/local/go/src/fmt --http
```

2020-09-17 13:28 UTC, smowton approved these changes

2020-09-21 13:56 UTC, max-schaefer requested changes
LGTM, but I'd like to tack on a few small consistency improvements if I may.

2020-09-21 13:56 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/Fmt.qll
> +  /** The `Scan` function or one of its variants, all of which read from os.Stdin */
```suggestion
  /** The `Scan` function or one of its variants, all of which read from `os.Stdin`. */
```

2020-09-21 13:56 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/Fmt.qll
> +   * all of which read from a specified io.Reader
```suggestion
   * all of which read from a specified `io.Reader`.
```

2020-09-21 13:56 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/stdlib/Fmt.qll
> +     * Returns the node corresponding to the io.Reader
```suggestion
     * Gets the node corresponding to the `io.Reader`
```

2020-09-21 14:25 UTC, max-schaefer commented
![image](https://user-images.githubusercontent.com/54907921/93779267-aecb5100-fc1e-11ea-99ed-6bc11b2cfeb6.png)

Nice SHA you managed to hit there!

2020-09-21 14:26 UTC, max-schaefer approved these changes

2020-09-21 14:34 UTC, gagliardetto commented
> ![image](https://user-images.githubusercontent.com/54907921/93779267-aecb5100-fc1e-11ea-99ed-6bc11b2cfeb6.png)
> 
> Nice SHA you managed to hit there!

Nice! :sparkles:

2020-09-21 21:10 UTC, merged