Add models for the Echo framework
github/codeql-go pull request #344
Opened 2020-09-17 17:21 UTC by smowton

2020-09-18 14:00 UTC, max-schaefer requested changes
Basically LGTM, I only have a few minor comments.

2020-09-18 14:11 UTC, smowton commented
@max-schaefer changes applied

2020-09-18 15:22 UTC, owen-mc approved these changes

2020-09-18 22:37 UTC, intrigus-lgtm commented on ql/src/semmle/go/frameworks/HTTP.qll
> +        fieldName = "PostForm" or
Could be changed to use set literals instead.

2020-09-21 13:49 UTC, max-schaefer requested changes
LGTM, I only have a few superficial comments and suggestions.

2020-09-21 13:49 UTC, max-schaefer commented on ql/src/semmle/go/Concepts.qll
> +     * open redirect exploits.
Perhaps worth adding an example of such an attribute.

2020-09-21 13:49 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Echo.qll
> +  private string packagePath() { result = "github.com/labstack/echo/v4" }
Are we specifically only interested in `v4`, or do we want to include earlier versions as well? If the latter, consider using the `package` predicate.

2020-09-21 13:49 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Echo.qll
> +                  "FormParams", "FormFile", "MultipartForm", "Cookie", "Cookies"]) and
The line breaks end up looking a little awkward, and I believe that's by design: @aschackmull is indirectly telling you to simplify this formula. How about pulling out the method name into a separate variable, for example?

2020-09-21 13:49 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Echo.qll
> +              ["FormValue", "FormParams", "FormFile", "MultipartForm", "Cookie", "Cookies"]) and
Ditto.

2020-09-21 13:49 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Echo.qll
> +        this = any(FunctionOutput output | output.isParameter(0)).getExitNode(call)
I've found myself writing an awkward `any` like this before. Perhaps it's time to introduce a helper?

```ql
module FunctionOutput {
  FunctionOutput parameter(int i) { result.isParameter(i) }
}
```

would allow us to write

```ql
this = FunctionOutput::parameter(0).getExitNode(call)
```

2020-09-21 13:49 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Echo.qll
> +        any(Method m | m.hasQualifiedName(packagePath(), "Context", ["HTML", "HTMLBlob"]))
I think this would read nicer as an `exists`.

2020-09-21 13:49 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Echo.qll
> +        any(Method m | m.hasQualifiedName(packagePath(), "Context", ["HTML", "HTMLBlob"]))
Several other instances below.

2020-09-21 15:24 UTC, smowton commented
@max-schaefer all changes applied.

2020-09-21 15:45 UTC, max-schaefer requested changes
Apologies, I think my suggestion for extracting out the method names was badly phrased. Tried to fix that, and added a few more very minor things.

2020-09-21 15:45 UTC, max-schaefer commented on ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
> +  /** Gets a FunctionInput representing the receiver. */
```suggestion
  /** Gets a `FunctionInput` representing the receiver. */
```

2020-09-21 15:45 UTC, max-schaefer commented on ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
> +  /** Gets a FunctionOutput representing the receiver after a function returns. */
```suggestion
  /** Gets a `FunctionOutput` representing the receiver after a function returns. */
```

2020-09-21 15:45 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Echo.qll
> +  private string getASourceMethodName() {
Any particular reason to extract this into a predicate instead of a variable? The latter has the advantage of keeping the definitions closer together.

2020-09-21 15:45 UTC, max-schaefer commented on ql/src/semmle/go/frameworks/Echo.qll
> +        this = FunctionOutput::parameter(0).getExitNode(call)
:+1: There are two other uses of `any(FunctionOutput ...).getExitNode(...)` elsewhere (not introduced by this PR). Perhaps update at the same time? Otherwise we'll probably just forget about them.

2020-09-21 16:08 UTC, smowton commented
@max-schaefer all done

2020-09-22 09:44 UTC, max-schaefer approved these changes

2020-09-22 09:45 UTC, merged