Add query spotting probably-bad escapes in regular expressions.
github/codeql-go pull request #350
Opened 2020-09-22 19:08 UTC by smowton

Inspired by js/useless-regexp-character-escape, but much much simpler because the Go source code parser forbids unrecognised escapes and its regex engine refuses to compile \\x where x is not a character class or other special token (e.g. start-of-word).

Evaluated on lgtm.com, found two results, one probable and one true positive, so clearly this is a much rarer mistake in Go than in JS, but I figure it doesn't hurt to have the query.

2020-09-23 07:11 UTC, sauyon reviewed
Generally looks good. Could you add some tests

2020-09-23 07:11 UTC, sauyon commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +  exists(source.getStringValue().regexpFind("\\u0007", _, _)) and
Would it make sense to use `regexpMatch` here and below?

2020-09-23 07:11 UTC, sauyon commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexpGood.go
> +	var htmlRe = regexp.MustCompile("\\bforbidden.host.org")
Perhaps we could recommend using raw string literals here? They're used in the `regexp` documentation and seem a bit nicer.

```suggestion
	var htmlRe = regexp.MustCompile(`\bforbidden.host.org`)
```

2020-09-23 08:14 UTC, max-schaefer requested changes
One question (twice), and I agree tests would be nice. Also needs :eyes: from @shati-patel.

2020-09-23 08:14 UTC, max-schaefer commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +  not source.(DataFlow::ExprNode).asExpr().(BasicLit).getText().matches(["%\\u0007%", "%\\x07%"])
I'm probably missing some subtlety, but given that you require `source` to be a `BasicLit` anyway, couldn't you just do

```suggestion
  source.asExpr().(BasicLit).getText().regexpMatch(".*(?<!\\\\)\\\\a.*")
```

2020-09-23 08:14 UTC, max-schaefer commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +predicate containsBackspaceCharacter(DataFlow::Node source) {
Same question as above.

2020-09-23 08:19 UTC, smowton commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +  not source.(DataFlow::ExprNode).asExpr().(BasicLit).getText().matches(["%\\u0007%", "%\\x07%"])
I was trying to avoid probably screwing up counting preceding backslashes by simply searching for an actual bell character in the cooked output. Can go for the regex-only version if you're happy to vouch for its correctness though!

2020-09-23 08:21 UTC, smowton commented
Applied @sauyon's requests (and added tests that I'd written but not checked in, doh)

2020-09-23 08:33 UTC, max-schaefer commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +  not source.(DataFlow::ExprNode).asExpr().(BasicLit).getText().matches(["%\\u0007%", "%\\x07%"])
> if you're happy to vouch for its correctness

I'll let the tests vouch for that :smirk:

2020-09-23 08:34 UTC, max-schaefer commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +  not source.(DataFlow::ExprNode).asExpr().(BasicLit).getText().matches(["%\\u0007%", "%\\x07%"])
> by simply searching for an actual bell character in the cooked output.

It's admittedly an edge case, but that version has the additional weakness that it won't flag strings containing both an `\a` and an `\x07`.

2020-09-23 08:52 UTC, smowton commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +  not source.(DataFlow::ExprNode).asExpr().(BasicLit).getText().matches(["%\\u0007%", "%\\x07%"])
That regex didn't work, but one pinched from https://github.com/github/codeql/blob/main/javascript/ql/src/semmle/javascript/CharacterEscapes.qll#L28 did.

2020-09-23 09:24 UTC, shati-patel reviewed
Here are some tiny docs suggestions! 📝

2020-09-23 09:24 UTC, shati-patel commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.qhelp
> +      matching any alphabetic character. Second <code>regexp.Compile("\b")</code>
```suggestion
      matching any alphabetic character. Second, <code>regexp.Compile("\b")</code>
```

2020-09-23 09:24 UTC, shati-patel commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.qhelp
> +      Ensure that the right amount of backslashes is used when
```suggestion
      Ensure that the right number of backslashes is used when
```

2020-09-23 09:24 UTC, shati-patel commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.qhelp
> +    <li>Google: <a href="https://github.com/google/re2/wiki/Syntax">Syntax of regular expressions accepted by RE2</a></li>
```suggestion
    <li>golang.org: <a href="https://golang.org/pkg/regexp/">Overview of the Regexp package</a>.</li>
    <li>Google: <a href="https://github.com/google/re2/wiki/Syntax">Syntax of regular expressions accepted by RE2</a>.</li>
```

2020-09-23 09:24 UTC, shati-patel commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.qhelp
> +    escape sequence.
```suggestion
    Alternatively, you can use backtick-delimited raw string literals. 
    For example, the <code>\b</code> in <code>regexp.Compile(`hello\bworld`)</code>
    matches a word boundary, not a backspace character, as within backticks <code>\b</code> is not an
    escape sequence.
```

I think this rewording is a bit clearer 🤔

2020-09-23 09:31 UTC, smowton commented
Thanks @shati-patel, all changes accepted

2020-09-23 09:33 UTC, max-schaefer commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +    source.asExpr().(BasicLit).getText().regexpFind("(?<=(^|[^\\\\])\\\\(\\\\{2}){0,10})a", _, _)
Well, I suppose I asked for it.

Could you combine these two predicates to avoid us having this, uh, very impressive regex in our code base twice?

2020-09-23 09:38 UTC, smowton commented on ql/test/query-tests/Security/CWE-020/SuspiciousCharacterInRegexp/test.go
> +
Already present on lines 13 and 18

2020-09-23 09:39 UTC, max-schaefer commented on ql/test/query-tests/Security/CWE-020/SuspiciousCharacterInRegexp/test.go
> +
:+1:

2020-09-23 09:44 UTC, smowton commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +    source.asExpr().(BasicLit).getText().regexpFind("(?<=(^|[^\\\\])\\\\(\\\\{2}){0,10})a", _, _)
Oh go on then. Changed.

2020-09-23 13:51 UTC, max-schaefer requested changes
I'm not great at piecing together what alert messages will ultimately look like, but in this case it seems like they would start with a lower-case character, which would be inconsistent with other queries.

Otherwise LGTM.

2020-09-23 13:51 UTC, max-schaefer commented on ql/src/Security/CWE-020/SuspiciousCharacterInRegexp.ql
> +select source, source, sink, "$@ used $@ contains " + report, source, "a regular expression", sink,
```suggestion
select source, source, sink, "$@ used $@ contains " + report, source, "A regular expression", sink,
```

(Will need updates to expected outputs, I'm afraid.)

2020-09-23 14:41 UTC, smowton commented
@max-schaefer done

2020-09-23 14:41 UTC, smowton commented
Also made https://github.com/github/semmle-code/pull/37831 to preview qhelp

2020-09-24 08:48 UTC, max-schaefer approved these changes

2020-09-24 08:49 UTC, merged

2020-09-24 09:26 UTC, smowton commented
Qhelp previewing is currently blocked on a bug where submodule qhelp files are not enumerated -- once that's fixed I'll run a preview and make a followup if necessary.

2020-09-29 15:24 UTC, smowton commented
Finally managed to gen the help, looks ok I think:

# Suspicious characters in a regular expression
When a character in a string literal or regular expression literal is preceded by a backslash, it is interpreted as part of an escape sequence. For example, the escape sequence `\n` in a string literal corresponds to a single `newline` character, and not the `\` and `n` characters. There are two Go escape sequences that could produce surprising results. First, `regexp.Compile("\a")` matches the bell character, whereas `regexp.Compile("\\A")` matches the start of text and `regexp.Compile("\\a")` is a Vim (but not Go) regular expression matching any alphabetic character. Second, `regexp.Compile("\b")` matches a backspace, whereas `regexp.Compile("\\b")` matches the start of a word. Confusing one for the other could lead to a regular expression passing or failing much more often than expected, with potential security consequences. Note this is less of a problem than in some other languages because in Go, only valid escape sequences are accepted, both in an ordinary string (for example, `s := "\k"` will not compile as there is no such escape sequence) and in regular expressions (for example, `regexp.MustCompile("\\k")` will panic as `\k` does not refer to a character class or other special token according to Go's regular expression grammar).


## Recommendation
Ensure that the right number of backslashes is used when escaping characters in strings and regular expressions.


## Example
The following example code fails to check for a forbidden word in an input string:


```go
package main

import "regexp"

func broken(hostNames []byte) string {
	var htmlRe = regexp.MustCompile("\bforbidden.host.org")
	if htmlRe.Match(hostNames) {
		return "Must not target forbidden.host.org"
	} else {
		// This will be reached even if hostNames is exactly "forbidden.host.org",
		// because the literal backspace is not matched
	}
}

```
The check does not work, but can be fixed by escaping the backslash:


```go
package main

import "regexp"

func fixed(hostNames []byte) string {
	var htmlRe = regexp.MustCompile("\\bforbidden.host.org")
	if htmlRe.Match(hostNames) {
		return "Must not target forbidden.host.org"
	} else {
		// hostNames definitely doesn't contain a word "forbidden.host.org", as "\\b"
		// is the start-of-word anchor, not a literal backspace.
	}
}

```
Alternatively, you can use backtick-delimited raw string literals. For example, the `\b` in `regexp.Compile(`hello\bworld`)` matches a word boundary, not a backspace character, as within backticks `\b` is not an escape sequence.


## References
* golang.org: [Overview of the Regexp package](https://golang.org/pkg/regexp/).
* Google: [Syntax of regular expressions accepted by RE2](https://github.com/google/re2/wiki/Syntax).
* Common Weakness Enumeration: [CWE-20](https://cwe.mitre.org/data/definitions/20.html).

2020-09-29 15:37 UTC, smowton commented
https://github.com/github/codeql-go/pull/359 the other formatting problem turns out to be a qhelp-to-markdown bug

2020-09-29 15:52 UTC, smowton commented
Looks like the bug relates to escaping backticks within code elements, and is fixed by https://github.com/github/semmle-code/commit/816eba651efa15cd8e1a9dd275372f9e1db0c773 which is not in the 2.3.0 release.