Miscellaneous extractor improvements
github/codeql-go pull request #355
Opened 2020-09-24 09:32 UTC by sauyon

These changes are mostly changes that were for Kubernetes.

 - Package directory as a wanted root
  
   This makes the extractor actually extract vendor packages when they're explicitly passed to a build command; before the wanted root would be the mod directory, and so the all the files would because the relative path to the root includes `vendor`. I'm not 100% sure we should do this, but that was my intention when I made the original changes, so I've changed this.

 - Enable Go modules while determining module directory

   This force enables modules while running `go list -f {{.Module}} ...` so that even if `GO111MODULE=off` is set manually, we can still detect module directory. This is done by Kubernetes, and the change increases the coverage of the database significantly.

 - Improve extractor logging

   Added a bunch of miscellaneous logging. I've discovered that a lot of the time spent extracting is actually spent in the single-threaded bit where we walk dependencies and extract types; ideally we'd be able to parallelize that a bit with a topological sort or something similar.

2020-09-24 09:42 UTC, smowton requested changes
Please add some tests; what's the eval status here?

2020-09-24 09:42 UTC, smowton commented on extractor/extractor.go
> +	modEnabled := os.Getenv("GO111MODULE") == "off"
This is backwards

2020-09-24 09:42 UTC, smowton commented on extractor/extractor.go
> +	log.Println("Running Go frontend.")
Make more precise: `Running packages.Load`

2020-09-24 09:42 UTC, smowton commented on extractor/util/util.go
> +	cmd.Env = append(os.Environ(), additionalEnv...)
To check: is `append` sufficient if the var is already present in the envrionment?

2020-09-24 09:42 UTC, smowton commented on extractor/util/util.go
> +	mod, err := runGoListWithEnv("{{.Module}}", pkgpath, []string{"GO111MODULE=on"}, flags...)
Comment here on why you force-enable module mode

2020-09-24 09:46 UTC, sauyon commented on extractor/util/util.go
> +	cmd.Env = append(os.Environ(), additionalEnv...)
Yep

2020-09-24 09:49 UTC, sauyon commented
I don't think I can add tests under our current framework because of the limitation on `qltest` where we can't specify build commands.

I haven't actually run any evaluations on this. Maybe I should have included this in the build tracing PR, since it's all only relevant to traced builds (I think).

2020-09-24 09:53 UTC, smowton commented
Could you also do an lgtm-distribution test to check whether this derails any existing projects?

2020-09-24 09:54 UTC, smowton commented
Tests: I suppose I was imagining some project in `extractor-tests` that extracts usefully with these changes but not without them, something to ensure this is providing the value it's supposed to

2020-09-24 09:56 UTC, sauyon commented
> Tests: I suppose I was imagining some project in `extractor-tests` that extracts usefully with these changes but not without them, something to ensure this is providing the value it's supposed to

The issue is that I don't think this should change anything for non-traced builds, which I believe is the only thing we can test at the moment (@max-schaefer?).

2020-09-24 09:58 UTC, sauyon commented
Actually, I'll just fold everything but the logging changes into the build-tracing PR; I think that makes more sense.

2020-09-24 10:26 UTC, smowton approved these changes
LGTM

2020-09-25 10:57 UTC, max-schaefer requested changes

2020-09-25 10:57 UTC, max-schaefer commented on extractor/extractor.go
> +		log.Printf("Processing package %s.", pkg.PkgPath)
Does this (and the other uses of `Printf`) want a final `\n`, or do we get that from somewhere else?

2020-09-25 10:57 UTC, max-schaefer commented on extractor/extractor.go
> +		log.Printf("Skipping dependency package %s", pkg.PkgPath)
```suggestion
		log.Printf("Skipping dependency package %s.", pkg.PkgPath)
```

2020-09-25 10:59 UTC, sauyon commented on extractor/extractor.go
> +		log.Printf("Processing package %s.", pkg.PkgPath)
For some reason `log.Printf` adds a newline at the end.

2020-09-25 11:24 UTC, sauyon commented
Made the changes and rebased.

2020-09-25 12:39 UTC, max-schaefer commented on extractor/extractor.go
> +		log.Printf("Processing package %s.", pkg.PkgPath)
:+1:

2020-09-25 12:39 UTC, max-schaefer approved these changes

2020-09-25 12:44 UTC, merged