CFG: fix lastNode relating to assignments with underscores on the LHS
github/codeql-go pull request #393
Opened 2020-11-02 17:46 UTC by smowton

For example, "x, _ := a, b" would produce an incorrect CSV that branched to the next statement after evaluating "b", skipping the assignment to 'x'. We already had test coverage for function returns, so I'm reasonably confident this only affects parallel assigns, not destructuring ones like "x, y := f()".

2020-11-02 17:49 UTC, smowton commented
Distcompare underway. Note to reviewers: the division between `succ` and the epilogue was rejigged so that the epilogue functions didn't recurse into lastNode, enabling me to use it in defining lastNode.

2020-11-02 17:53 UTC, smowton commented
There's also one incidental test change which I consider an improvement, branching from `var _ int`'s implicit zero to the next instruction, rather than bypassing it entirely.

2020-11-03 10:25 UTC, max-schaefer requested changes
Phew, subtle stuff, but I think I can see how it works. Only some minor comments from my side, and then we'll see what the evaluation says.

2020-11-03 10:25 UTC, max-schaefer commented on ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
> +        last = max(int i | any() | epilogueNode(i) order by i)
```suggestion
        last = max(int i | | epilogueNode(i) order by i)
```

2020-11-03 10:25 UTC, max-schaefer commented on ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
> +      result = max(int i | any() | getSubExprInEvalOrder(i) order by i)
```suggestion
      result = max(int i | | getSubExprInEvalOrder(i) order by i)
```

2020-11-03 10:25 UTC, max-schaefer commented on ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
> +      else result = getRhs(evalOrder - getNumLhs())
I think this is equivalent to

```suggestion
      result = getLhs(evalOrder) or result = getRhs(evalOrder - getNumLhs())
```

(since `getLhs(evalOrder)` isn't defined for `evalOrder >= getNumLhs()`, and similarly for `getRhs(evalOrder - getNumLhs())`) but feel free to keep the current implementation if you prefer it for clarity.

2020-11-03 11:59 UTC, smowton commented on ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
> +      else result = getRhs(evalOrder - getNumLhs())
I'll opt for clarity here :)

2020-11-03 11:59 UTC, smowton commented on ql/src/semmle/go/controlflow/ControlFlowGraphImpl.qll
> +        last = max(int i | any() | epilogueNode(i) order by i)
Adding this to the list of "syntax I would have confidently wagered against compiling" :)

2020-11-03 12:01 UTC, smowton commented
The distcompare results are blessedly, beautifully boring. Other changes applied.

2020-11-03 13:02 UTC, sauyon approved these changes
LGTM.

How did we get the extra node from `var _ int`, though? Shouldn't `lastNode(getLhs(nl - 1), last, normalCompletion())` be the same as `lastNode(getLastSubExprInEvalOrder(), last, normalCompletion())`?

2020-11-03 13:59 UTC, smowton commented
It's because `getRhs` has no results (`var _ int` doesn't specify any RHS), but there is a `MkZeroInitNode` representing the implicit zero. The old version generated a `succ` pointing to it as part of the epilogue, but called the `skip` for LHS evaluation the end of the statement's CFG, with the zero ending up orphaned. Now we include the zero because it's generated in the epilogue. 

We couldsuppress a zero which is certain to be discarded, similar to how the MkAssignNode is not generated when the LHS is discarded, but while it is generated, it's best not to make orphaned CFG nodes.

2020-11-03 14:06 UTC, max-schaefer approved these changes

2020-11-03 14:32 UTC, merged

2021-02-11 21:08 UTC, betadae reviewed
@tfgrimes Carrier:MTN, wallet number:0594423558
Amount :$4000[http:\\betadaemusic.woedpress.com](154.160.7.73)