Pilot #0: Add web framework `clevergo`
github/codeql-go pull request #438
Opened 2020-12-20 22:44 UTC by gagliardetto

This is a "pilot" batch (of 1 element) for a project targeting web frameworks.

Let me know your thoughts.

2020-12-20 22:56 UTC, gagliardetto commented
Right now the tool can handle the `UntrustedFlowSource` and `TaintTracking` models.

Given that I don't want to open more than one PR (ever) for any given web framework, I want to be sure I get the most important models right from the start. It's like going to the grocery store; I want to get everything the first time I go there.

This is the list of models I want to add:

1. `HTTP::Redirect::Range`
1. `HTTP::ResponseBody::Range`

Those two seem like the most impactful. Anything else?

2020-12-20 23:06 UTC, gagliardetto commented
Maybe also:

1. `HTTP::Redirect::UnexploitableSource`
2. `TaintTracking::DefaultTaintSanitizer`

I'm aiming at having the most impact, rather than completeness. The most bang for the buck.

2020-12-21 13:25 UTC, smowton commented
Most of the Go team is out for the holidays now, so I'll look on the 4th January or later

2020-12-21 14:09 UTC, gagliardetto commented
Sounds great! Thanks! Happy holidays

2020-12-21 14:11 UTC, smowton commented
You too :)

2020-12-21 17:14 UTC, airairair20 requested changes

2020-12-21 17:14 UTC, airairair20 commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +import go
[](https://support.google.com/chrome/answer/95617?visit_id=63741205695040819
```suggestion
import go
```
-2956743203&_p_=ui_security_indicator&rd=1)

2020-12-21 17:26 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +import go
???

2020-12-22 22:19 UTC, sauyon reviewed
Thanks again, I should really try to get the tool working so I can use it myself.

I haven't actually looked at the models themselves, but a few comments on the generator.

2020-12-22 22:19 UTC, sauyon commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        hasQualifiedName(packagePath(), "CleanPath") and
Would prefer `this.hasQualifiedName` here and `this.implements` below.

2020-12-22 22:19 UTC, sauyon commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        implements(packagePath(), "Decoder", "Decode") and
Why aren't these separated by receiver like the methods above?

2020-12-22 22:19 UTC, sauyon commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        )
I think I would prefer there not to be parentheses here.

2020-12-22 22:19 UTC, sauyon commented on ql/test/library-tests/semmle/go/frameworks/CleverGo/TaintTracking/Test.ql
> +  override string getARelevantTag() { result = "SinkingSource" }
```suggestion
  override string getARelevantTag() { result = "taintSink" }
```

2020-12-22 22:19 UTC, sauyon commented on ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources/Test.ql
> +class UntrustedFlowSourceTest extends InlineExpectationsTest {
I guess these are in separate files to avoid flagging untrusted flow sources in the taint tests?

You could just put the tests in separate files or functions and separate them that way, I think that would be cleaner.

2020-12-22 22:19 UTC, sauyon commented on ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources/Test.ql
> +  override string getARelevantTag() { result = "SinkingUntrustedFlowSource" }
```suggestion
  override string getARelevantTag() { result = "untrustedFlowSource" }
```

2020-12-22 23:45 UTC, gagliardetto commented
> Thanks again, I should really try to get the tool working so I can use it myself.

Thanks for the review! This is actually not `codebox` but another tool I recently wrote from (almost) scratch. There are a few things I want to do with it before I opensource it.

2020-12-22 23:46 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  string packagePath() { result = ["clevergo.tech/clevergo", "github.com/clevergo/clevergo"] }
I've seen this around; what does `package(...)` do that a string can't?

2020-12-23 00:02 UTC, sauyon commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  string packagePath() { result = ["clevergo.tech/clevergo", "github.com/clevergo/clevergo"] }
It allows for versions at the end of the module path.

2020-12-23 00:11 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  string packagePath() { result = ["clevergo.tech/clevergo", "github.com/clevergo/clevergo"] }
Ooh, that's useful.

2020-12-23 00:38 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        hasQualifiedName(packagePath(), "CleanPath") and
You mean using `this` everywhere?

2020-12-23 00:41 UTC, gagliardetto commented on ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources/Test.ql
> +class UntrustedFlowSourceTest extends InlineExpectationsTest {
Tests are separated into folders by model kind. Each model kind has its own test folder.

That is done by the generator, that doesn't try to merge things together.

But it does generate only one .qll file.

2020-12-23 00:42 UTC, gagliardetto commented on ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources/Test.ql
> +class UntrustedFlowSourceTest extends InlineExpectationsTest {
But yeah, here I could use the same go.mod file and vendor folder.

2020-12-23 00:44 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        implements(packagePath(), "Decoder", "Decode") and
Should they be separated by receiver here, too?

2020-12-23 01:26 UTC, gagliardetto commented
@sauyon 

I have a list of projects I want to complete using my tool (the first one being: model most web frameworks; other projects have the same spirit for SystemExecutors, log libraries, etc. Anything there's a concept defined for.)

If you and anyone on the Go team are interested in seeing/contributing/using the tool, I could maybe sometime add you as collaborators, **provided that will not impact my ability to carry forward with the above said projects** 😗

Happy holidays! Until next year

2021-01-04 12:18 UTC, smowton reviewed
You can see some of the other common `::Range` classes used in the newly-added Beego models (https://github.com/github/codeql-go/blob/main/ql/src/semmle/go/frameworks/Beego.qll)

Particularly `HeaderWrite` and `ResponseWriter`, which are used to pair up a response body with its content-type. Note that there are methods that set both simultaneously (e.g. `response.JSON(xyz)`), those that explicitly set content-type (`response.SetContentType("text/html"); response.Write(xyz)`) and those that set a generic HTTP header which could be Content-Type (`response.SetHeader("Content-Type", "text/html"); response.Write(xyz)`)

2021-01-04 12:18 UTC, smowton commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  bindingset[result]
I think the `bindingset` should be unnecessary

2021-01-04 12:18 UTC, smowton commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        hasQualifiedName(packagePath(), "CleanPath") and
Yes, it's conventional

2021-01-05 22:59 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> + * TODO: Doc about this file.
Done.

2021-01-05 22:59 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  string packagePath() { result = ["clevergo.tech/clevergo", "github.com/clevergo/clevergo"] }
Done.

2021-01-05 22:59 UTC, intrigus-lgtm commented on ql/src/semmle/go/frameworks/CleverGo.qll
> + * Provides classes for working with concepts from [`clevergo.tech/clevergo@v0.5.2`](https://pkg.go.dev/clevergo.tech/clevergo@v0.5.2) package.
Not 100% sure, but shouldn't this be using a *the*?

```suggestion
 * Provides classes for working with concepts from the [`clevergo.tech/clevergo@v0.5.2`](https://pkg.go.dev/clevergo.tech/clevergo@v0.5.2) package.
```

2021-01-05 22:59 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        this = read
Done.

2021-01-05 23:00 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        mtd.hasQualifiedName(packagePath(), "Context", methodName) and
Could I keep it as-is?

2021-01-05 23:01 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        implements(packagePath(), "Decoder", "Decode") and
Done.

2021-01-05 23:01 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        )
Done.

2021-01-05 23:01 UTC, gagliardetto commented on ql/test/library-tests/semmle/go/frameworks/CleverGo/TaintTracking/Test.ql
> +  override string getARelevantTag() { result = "SinkingSource" }
Done.

2021-01-05 23:01 UTC, gagliardetto commented on ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources/Test.ql
> +  override string getARelevantTag() { result = "SinkingUntrustedFlowSource" }
Done.

2021-01-05 23:05 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  bindingset[result]
Done.

2021-01-05 23:12 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  bindingset[result]
It actually needs it.

```bash
Executing 1 tests in 1 directories.
Extracting test database in /home/laptop/vscode-codeql-starter/codeql-go/ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources.
Compiling queries in /home/laptop/vscode-codeql-starter/codeql-go/ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources.
--- expected
+++ actual
@@ -1,1 +1,2 @@
-
+ERROR: 'result' is not bound to a value. (/home/laptop/vscode-codeql-starter/codeql-go/ql/src/semmle/go/frameworks/CleverGo.qll:12,3-9)
+ERROR: expression is not bound to a value. (/home/laptop/vscode-codeql-starter/codeql-go/ql/src/semmle/go/frameworks/CleverGo.qll:13,14-85)
[1/1 comp 4.4s] FAILED(COMPILATION) /home/laptop/vscode-codeql-starter/codeql-go/ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources/Test.ql
0 tests passed; 1 tests failed:
  FAILED: /home/laptop/vscode-codeql-starter/codeql-go/ql/test/library-tests/semmle/go/frameworks/CleverGo/UntrustedSources/Test.ql
```

2021-01-05 23:35 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  bindingset[result]
> You can see some of the other common ::Range classes used in the newly-added Beego models (https://github.com/github/codeql-go/blob/main/ql/src/semmle/go/frameworks/Beego.qll)

Thanks! That's a dense model.

2021-01-05 23:44 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> + * Provides classes for working with concepts from [`clevergo.tech/clevergo@v0.5.2`](https://pkg.go.dev/clevergo.tech/clevergo@v0.5.2) package.
Sounds better, yeah. Thanks!

2021-01-06 09:55 UTC, smowton commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  bindingset[result]
Ah, that's why -- when originally reviewed this was an equality constraint, now it uses `package` which in turn uses regexes.

2021-01-06 10:03 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +  bindingset[result]
Makes sense.

2021-01-06 18:03 UTC, sauyon commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        mtd.hasQualifiedName(packagePath(), "Context", methodName) and
No performance impact; I just think it would be as clear as the comment is at the moment.

Not that it isn't clear as-is, probably the comment isn't super necessary.

2021-01-23 09:37 UTC, gagliardetto commented on ql/src/semmle/go/frameworks/CleverGo.qll
> +        mtd.hasQualifiedName(packagePath(), "Context", methodName) and
Yeah. Fixed.

2021-01-24 17:12 UTC, gagliardetto commented
Next I'm going to add `HTTP::Redirect`.

I'm thinking it could look like this:

```codeql

  private class RedirectMethods2 extends HTTP::Redirect::Range, DataFlow::CallNode {
    string package;
    DataFlow::Node urlNode;

    RedirectMethods2() {
      package = packagePath() and
      (
        // Function call:
        this.getTarget().hasQualifiedName(package, "DoRedirect") and
        urlNode = this.getArgument(2)
        or
        // Method on type call:
        this = any(Method m | m.hasQualifiedName(package, "SomeReceiver", "Redirect")).getACall() and
        urlNode = this.getArgument(1)
        or
        // Method on interface call:
        this = any(Method m | m.implements(package, "SomeInterface", "Redirect")).getACall() and
        urlNode = this.getArgument(1)
      )
    }

    override DataFlow::Node getUrl() { result = urlNode }

    //    override HTTP::ResponseWriter getResponseWriter() { result.getANode() = this.getReceiver() }
    override HTTP::ResponseWriter getResponseWriter() { none() }
  }
```

**Questions:**

1. What is `getResponseWriter()` exactly for?
2. Is having `getResponseWriter()` impactful?

Thanks!

2021-01-25 11:37 UTC, smowton commented
For header writes, `getResponseWriter` is for pairing up a header-set operation with the corresponding response body, which the XSS query uses to exclude bodies accompanied by a non-HTML content-type. For HTTP::Redirect it doesn't appear to be used at the moment, so can be safely set to `none()` and perhaps ought to be removed.

2021-01-25 13:08 UTC, gagliardetto commented
Thanks @smowton 

And how does the proposed model look to you?

2021-01-25 15:21 UTC, smowton commented
Looks good to me -- @sauyon you have any further comments?

2021-01-25 16:27 UTC, gagliardetto commented
Added the modelling for HTTP redirects.

Not sure about the correctness of the inline tests; does ql/test/library-tests/semmle/go/frameworks/CleverGo/HttpRedirect/Test.ql actually catch what it is supposed to catch?

2021-01-25 17:39 UTC, gagliardetto commented
Once the `HTTP::Redirect` model is approved, I'll move on to adding another kind of model (haven't decided which yet).

When a number of model kinds are implemented, I'll tidy up this PR to be merged (things like removing duplicate vendoring, etc.).

2021-01-26 17:00 UTC, gagliardetto commented
Next up: `HTTP::ResponseBody`

```codeql
  private class ResponseBody extends HTTP::ResponseBody::Range {
    string package;
    DataFlow::CallNode call;
    string contentType;

    ResponseBody() {
      package = packagePath() and
      (
        // Function call:
        call.getTarget().hasQualifiedName(package, "JSON") and
        this = call.getArgument(1) and
        contentType = "application/json"
        or
        // Method on type call:
        call = any(Method m | m.hasQualifiedName(package, "SomeReceiver", "JSON")).getACall() and
        this = call.getArgument(0) and
        contentType = "application/json"
        or
        // Method on interface call:
        call = any(Method m | m.implements(package, "SomeInterface", "JSON")).getACall() and
        this = call.getArgument(0) and
        contentType = "application/json"
      )
    }

    override string getAContentType() { result = contentType }

    override HTTP::ResponseWriter getResponseWriter() { none() }
  }
```

**Questions**:

1. What is `getResponseWriter()` exactly for?
2. Is having `getResponseWriter()` impactful?

2021-01-27 06:01 UTC, sauyon commented
>     1. What is `getResponseWriter()` exactly for?

For linking response writes with other response writes and headers. If the model has another way of achieving this, omitting it is fine.

2021-01-27 06:02 UTC, sauyon commented
> Not sure about the correctness of the inline tests query; does https://github.com/github/codeql-go/blob/9d6ac53acff98b33aacc1c7824670518e83eb4f7/ql/test/library-tests/semmle/go/frameworks/CleverGo/HttpRedirect/Test.ql actually catch what it is supposed to catch? Do they make sense?

The inline test query makes sense to me; was there a problem with it?

2021-01-27 14:48 UTC, gagliardetto commented
> > Not sure about the correctness of the inline tests query; does https://github.com/github/codeql-go/blob/9d6ac53acff98b33aacc1c7824670518e83eb4f7/ql/test/library-tests/semmle/go/frameworks/CleverGo/HttpRedirect/Test.ql actually catch what it is supposed to catch? Do they make sense?
> 
> The inline test query makes sense to me; was there a problem with it?

Nope. Just wanted to makes sure it made sense.

2021-01-27 16:37 UTC, gagliardetto commented
Added `HTTP::ResponseBody` modelling.

Next will think about `HTTP::ResponseWriter`. Still not sure about how it works and relates to the `getResponseWriter()` methods.

2021-02-03 18:09 UTC, gagliardetto commented
Got a few more scenarios of `ResponseBody` without using `HTTP::ResponseWriter` (I hope that's OK).

2021-02-03 18:10 UTC, gagliardetto commented
Example:

```golang
// Code generated by https://github.com/gagliardetto. DO NOT EDIT.

//go:generate depstubber --vendor --auto
package main

func main() {}
func source() interface{} {
	return nil
}

type Context struct{}

//
func (ctx *Context) JSON(code int, body interface{}) error {
	return nil
}

//
func (ctx *Context) Resp(code int, contentType string, body interface{}) error {
	return nil
}

//
func (ctx *Context) SetContentType(contentType string) error {
	return nil
}

//
func (ctx *Context) SetBody(body interface{}) error {
	return nil
}

//
func (ctx *Context) SetContentTypeJSON() error {
	return nil
}

//
func (ctx *Context) SetHeader(key string, val string) error {
	return nil
}

//
func (ctx *Context) Redirect(code int, url string) error {
	return nil
}

func HttpResponseWriter() {
	{
		body111 := source()
		var rece Context
		rece.JSON(200, body111) // $contentType=application/json $responseBody=body111
	}
	{
		body222 := source()
		var rece Context
		rece.Resp(200, "application/json", body222) // $contentType=application/json $responseBody=body222
	}
	{
		body333 := source()
		var rece Context
		rece.SetContentType("application/json")
		rece.SetBody(body333) // $contentType=application/json $responseBody=body333
	}
	{
		body444 := source()
		var rece Context
		rece.SetContentTypeJSON()
		rece.SetBody(body444) // $contentType=application/json $responseBody=body444
	}
	{
		body555 := source()
		var rece Context
		rece.SetHeader("content-type", "application/json")
		rece.SetBody(body555) // $contentType=application/json $responseBody=body555
	}
}
```

```codeql
/**
 * Provides classes for working with concepts from package.
 */

import go
import TestUtilities.InlineExpectationsTest
import go

/**
 * Provides classes for working with concepts from package.
 */
private module SomePackage {
  private class ContextHeaderWriteCall extends HTTP::HeaderWrite::Range, DataFlow::MethodCallNode {
    ContextHeaderWriteCall() {
      this = any(Method m | m.hasQualifiedName(_, "Context", "SetHeader")).getACall()
    }

    override DataFlow::Node getName() { result = this.getArgument(0) }

    override DataFlow::Node getValue() { result = this.getArgument(1) }

    override HTTP::ResponseWriter getResponseWriter() {
      result.getANode() = this.getReceiver().getAPredecessor*()
    }
  }

  /**
   * Models HTTP ResponseBody.
   */
  private class HttpResponseBody extends HTTP::ResponseBody::Range {
    DataFlow::CallNode bodySetterCall;
    string contentType;

    HttpResponseBody() {
      // Receiver type: Context
      // signature: func (*Context).JSON(code int, body interface{}) error
      bodySetterCall = any(Method m | m.hasQualifiedName(_, "Context", "JSON")).getACall() and
      this = bodySetterCall.getArgument(1) and
      contentType = "application/json"
      or
      // signature: func (*Context).Resp(code int, contentType string, body interface{}) error
      bodySetterCall = any(Method m | m.hasQualifiedName(_, "Context", "Resp")).getACall() and
      this = bodySetterCall.getArgument(2) and
      contentType = bodySetterCall.getArgument(1).getStringValue()
      or
      // signature: func (*Context).SetBody(body interface{}) error
      bodySetterCall = any(Method m | m.hasQualifiedName(_, "Context", "SetBody")).getACall() and
      this = bodySetterCall.getArgument(0) and
      // signature: func (*Context).SetContentType(contentType string) error
      exists(DataFlow::CallNode contentTypeSetterCall |
        contentTypeSetterCall =
          any(Method m | m.hasQualifiedName(_, "Context", "SetContentType")).getACall() and
        contentTypeSetterCall.getReceiver().getAPredecessor*() =
          bodySetterCall.getReceiver().getAPredecessor*()
      |
        contentType = contentTypeSetterCall.getArgument(0).getStringValue()
      )
      or
      // signature: func (*Context).SetBody(body interface{}) error
      bodySetterCall = any(Method m | m.hasQualifiedName(_, "Context", "SetBody")).getACall() and
      this = bodySetterCall.getArgument(0) and
      // signature: func (*Context).SetContentType(contentType string) error
      exists(DataFlow::CallNode contentTypeSetterCall |
        contentTypeSetterCall =
          any(Method m | m.hasQualifiedName(_, "Context", "SetContentTypeJSON")).getACall() and
        contentTypeSetterCall.getReceiver().getAPredecessor*() =
          bodySetterCall.getReceiver().getAPredecessor*()
      |
        contentType = "application/json"
      )
      or
      // signature: func (*Context).SetBody(body interface{}) error
      bodySetterCall = any(Method m | m.hasQualifiedName(_, "Context", "SetBody")).getACall() and
      this = bodySetterCall.getArgument(0) and
      // signature: func (*Context).SetHeader(key string, val string) error
      exists(ContextHeaderWriteCall hw |
        hw.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()
      |
        hw.getHeaderName() = "content-type" and
        contentType = hw.getValue().getStringValue()
      )
    }

    override string getAContentType() { result = contentType }

    override HTTP::ResponseWriter getResponseWriter() { none() }
  }
}

class HttpResponseBodyTest extends InlineExpectationsTest {
  HttpResponseBodyTest() { this = "HttpResponseBodyTest" }

  override string getARelevantTag() { result = ["contentType", "responseBody"] }

  override predicate hasActualResult(string file, int line, string element, string tag, string value) {
    exists(HTTP::ResponseBody rd |
      rd.hasLocationInfo(file, line, _, _, _) and
      (
        element = rd.getAContentType().toString() and
        value = rd.getAContentType().toString() and
        tag = "contentType"
        or
        element = rd.toString() and
        value = rd.toString() and
        tag = "responseBody"
      )
    )
  }
}
```

2021-02-09 16:24 UTC, gagliardetto commented
I added more `HTTP::ResponseBody` models and tests which consider all possible combinations.

## TODO:

- To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
- How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
- Add tests for the case where the `contentType` is set via a `HeaderWrite`.

2021-02-09 16:24 UTC, gagliardetto commented
I added more `HTTP::ResponseBody` models and tests which consider all possible combinations.

## TODO:

- To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
- How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
- Add tests for the case where the `contentType` is set via a `HeaderWrite`.

2021-02-09 16:24 UTC, gagliardetto commented
I added more `HTTP::ResponseBody` models and tests which consider all possible combinations.

## TODO:

- To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
- How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
- Add tests for the case where the `contentType` is set via a `HeaderWrite`.

2021-02-09 16:24 UTC, gagliardetto commented
I added more `HTTP::ResponseBody` models and tests which consider all possible combinations.

## TODO:

- To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
- How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
- Add tests for the case where the `contentType` is set via a `HeaderWrite`.

2021-02-09 16:24 UTC, gagliardetto commented
I added more `HTTP::ResponseBody` models and tests which consider all possible combinations.

## TODO:

- To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
- How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
- Add tests for the case where the `contentType` is set via a `HeaderWrite`.

2021-02-09 16:24 UTC, gagliardetto commented
I added more `HTTP::ResponseBody` models and tests which consider all possible combinations.

## TODO:

- To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
- How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
- Add tests for the case where the `contentType` is set via a `HeaderWrite`.

2021-02-09 16:25 UTC, gagliardetto commented
I added more `HTTP::ResponseBody` models and tests which consider all possible combinations.

## TODO:

- To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
- How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
- Add tests for the case where the `contentType` is set via a `HeaderWrite`.

2021-02-09 16:25 UTC, gagliardetto commented
I added more `HTTP::ResponseBody` models and tests which consider all possible combinations.

## TODO:

- To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
- How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
- Add tests for the case where the `contentType` is set via a `HeaderWrite`.

2021-02-09 17:21 UTC, gagliardetto commented
One thing to note is that the `Content-Type` header might look something like `text/html; charset=UTF-8`, and to match that you'd need some regex.

---

A second thing to note is that this code snippet from the tests does not work (using a variable for the contentType string):

```go
			// func (*Context).Blob(code int, contentType string, bs []byte) (err error)
			{
				bodyByte839 := source().([]byte)
				contentTypeString458 := "application/json"
				var rece clevergo.Context
				rece.Blob(0, contentTypeString458, bodyByte839) // $contentType=application/json $responseBody=bodyByte839
			}
```

I had to change it to this (the content-type is a string passed directly as parameter in the call):

```go
			// func (*Context).Blob(code int, contentType string, bs []byte) (err error)
			{
				bodyByte839 := source().([]byte)
				var rece clevergo.Context
				rece.Blob(0, "application/json", bodyByte839) // $contentType=application/json $responseBody=bodyByte839
			}
```

Maybe there's something wrong in the codeql models?

2021-02-18 23:03 UTC, gagliardetto commented
I'm kinda satisfied with how the generator looks right now. Might opensource soon.

2021-02-24 15:48 UTC, gagliardetto commented
@sauyon @smowton @owen-mc @max-schaefer I just made public the tool I used to generate this model: https://github.com/gagliardetto/codemill

2021-02-24 15:51 UTC, gagliardetto commented
I also released the library I created for generating codeql: https://github.com/gagliardetto/cqlgen

2021-04-07 15:30 UTC, gagliardetto commented
I realized that I had added this to the standard library instead of the experimental folder. Fixed.

2021-04-08 10:32 UTC, smowton commented
We should merge this soon, it's been languishing in review quite a long time. One note from a cursory review: can we structure the tests such that we don't have to duplicate the stubs of the clevergo framework in many places?

2021-04-08 17:12 UTC, gagliardetto commented
> can we structure the tests such that we don't have to duplicate the stubs of the clevergo framework in many places?

Done.

I thought there would be a lot of cross contamination, but I just had to add `$untrustedFlowSource` in a couple places inside https://github.com/github/codeql-go/blob/c127e5c33104b48db16d703d2bc4e1cd3edfa8ea/ql/test/experimental/frameworks/CleverGo/TaintTracking.go

2021-04-09 07:36 UTC, smowton approved these changes

2021-04-09 07:40 UTC, smowton commented
Rebased and merging on green

2021-04-09 07:40 UTC, smowton approved these changes

2021-04-09 08:48 UTC, merged

2021-04-09 09:00 UTC, gagliardetto commented
That's cool! But can you please help me solve the questions above?

Il ven 9 apr 2021, 10:49 Chris Smowton ***@***.***> ha
scritto:

> Merged #438 <https://github.com/github/codeql-go/pull/438> into main.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/codeql-go/pull/438#event-4573228738>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADUQNCLRJ42ICZ5DVNXNQVDTH25RDANCNFSM4VDODKZQ>
> .
>

2021-04-09 10:37 UTC, gagliardetto commented
More precisely, there are a couple questions and quirks I want to make sure
get solved before I proceed further:

https://github.com/github/codeql-go/pull/438#issuecomment-776062788

https://github.com/github/codeql-go/pull/438#issuecomment-776101825

2021-04-10 12:55 UTC, gagliardetto commented
For future reference, here is the codemill spec file for clevergo:

`CleverGo.json`:

```json
{
    "Name": "CleverGo",
    "Models": [
    {
        "Name": "UntrustedSources",
        "Kind": "UntrustedFlowSource",
        "Methods": [
        {
            "Name": "Self",
            "Selectors": [
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-BasicAuth",
                    "Pos": [false, true, true, false],
                    "Flows": null,
                    "Name": "BasicAuth"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-Decode",
                    "Pos": [false, true, false],
                    "Flows": null,
                    "Name": "Decode"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-DefaultQuery",
                    "Pos": [false, false, false, true],
                    "Flows": null,
                    "Name": "DefaultQuery"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-FormValue",
                    "Pos": [false, false, true],
                    "Flows": null,
                    "Name": "FormValue"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-GetHeader",
                    "Pos": [false, false, true],
                    "Flows": null,
                    "Name": "GetHeader"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-PostFormValue",
                    "Pos": [false, false, true],
                    "Flows": null,
                    "Name": "PostFormValue"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-QueryParam",
                    "Pos": [false, false, true],
                    "Flows": null,
                    "Name": "QueryParam"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-QueryString",
                    "Pos": [false, true],
                    "Flows": null,
                    "Name": "QueryString"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Params-String",
                    "Pos": [false, false, true],
                    "Flows": null,
                    "Name": "String"
                }
            },
            {
                "Kind": "Struct",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "Struct-Context",
                    "TypeName": "Context",
                    "Fields":
                    {
                        "Params": null
                    }
                }
            },
            {
                "Kind": "Struct",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "Struct-Param",
                    "TypeName": "Param",
                    "Fields":
                    {
                        "Key": null,
                        "Value": null
                    }
                }
            },
            {
                "Kind": "Type",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "Type-Params",
                    "TypeName": "Params",
                    "Value": true
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "InterfaceMethod-Decoder-Decode",
                    "Pos": [false, false, true, false],
                    "Flows": null,
                    "Name": "Decode"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "TypeMethod-Context-QueryParams",
                    "Pos": [false, true],
                    "Flows": null,
                    "Name": "QueryParams"
                }
            }]
        }]
    },
    {
        "Name": "TaintTracking",
        "Kind": "TaintTracking",
        "Methods": [
        {
            "Name": "Self",
            "Selectors": [
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "Function-CleanPath",
                    "Pos": null,
                    "Flows":
                    {
                        "Blocks": [
                        {
                            "Inp": [true, false],
                            "Out": [false, true]
                        }],
                        "Enabled": true
                    },
                    "Name": "CleanPath"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "InterfaceMethod-Decoder-Decode",
                    "Pos": null,
                    "Flows":
                    {
                        "Blocks": [
                        {
                            "Inp": [false, true, false, false],
                            "Out": [false, false, true, false]
                        }],
                        "Enabled": true
                    },
                    "Name": "Decode"
                }
            },
            {
                "Kind": "Func",
                "Qualifier":
                {
                    "Path": "clevergo.tech/clevergo",
                    "Version": "v0.5.2",
                    "ID": "InterfaceMethod-Renderer-Render",
                    "Pos": null,
                    "Flows":
                    {
                        "Blocks": [
                        {
                            "Inp": [false, false, false, true, false, false],
                            "Out": [false, true, false,  [...]

2021-04-12 08:25 UTC, sauyon commented
> One thing to note is that the `Content-Type` header value might look something like `text/html; charset=UTF-8`, and to match that you'd need some regex.

We just use `.*html.*`.

https://github.com/github/codeql-go/blob/dbcf1e1cfa5b072d9f06ec3f12df6b396681f192/ql/src/semmle/go/security/Xss.qll#L89-L91

> * To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?

That's fine. Elsewhere we use `VariableWithFields` as well as `.getAPredecessor*`, but I'm not sure it really adds much.

> * How would you implement `override HTTP::ResponseWriter getResponseWriter()`?

As this is only currently used in a not-very-nice way to link response writes and header writes together, possibly not at all. Perhaps a better interface here could be something like `.getAHeaderWrite` and / or `.getAnotherWrite` or something along those lines.

> * Add tests for the case where the `contentType` is set via a `HeaderWrite`.

No comments here.

> * Remove duplicate vendoring.

At some point I'd like to do this, but it's very much not a priority.

2021-04-12 12:33 UTC, gagliardetto commented
> > One thing to note is that the `Content-Type` header value might look something like `text/html; charset=UTF-8`, and to match that you'd need some regex.
> 
> We just use `.*html.*`.

Makes sense!

> > * To find whether methods are called on the same receiver, I use: `contentTypeSetterCall.getReceiver().getAPredecessor*() = bodySetterCall.getReceiver().getAPredecessor*()`; is that correct and a good way to do it?
> 
> That's fine. Elsewhere we use `VariableWithFields` as well as `.getAPredecessor*`, but I'm not sure it really adds much.

:+1: 



> > * How would you implement `override HTTP::ResponseWriter getResponseWriter()`?
> 
> As this is only currently used in a not-very-nice way to link response writes and header writes together, possibly not at all. Perhaps a better interface here could be something like `.getAHeaderWrite` and / or `.getAnotherWrite` or something along those lines.

I'll continue to leave `override HTTP::ResponseWriter getResponseWriter()` out of my models.


> > * Add tests for the case where the `contentType` is set via a `HeaderWrite`.
> 
> No comments here.

Forgot to cross that out. (Done)



> > * Remove duplicate vendoring.
> 
> At some point I'd like to do this, but it's very much not a priority.

Forgot to cross that out. (Done) (Was referring to the vendor duplication in clevergo tests)

Thanks @sauyon !