Add preliminary support for go 1.16
github/codeql-go pull request #480
Opened 2021-02-18 08:17 UTC by sauyon

Excludes treating embedded files as a variable initialization.

2021-02-18 10:28 UTC, owen-mc requested changes
- It would have been easier to review if this was split into separate commits for the different features being supported.
- What is the binary file `go1.16`?
- I expected `File.Read()` to be modelled, but I guess it's covered by `io.Reader.Read()`. It might be worth putting a test for it with the other `io/fs` tests.
- Can you add a test for the change you made to `Os.qll`? I can't find any tests for the rest of that predicate, so I accept this might be difficult.

2021-02-18 10:28 UTC, owen-mc commented on ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/IoFs.go
> +		fs.WalkDir(source, ".", func(path string, _ fs.DirEntry, _ error) error {
For one of the tests of `WalkDir`, how about using a function that's declared at file scope?

2021-02-18 11:01 UTC, smowton commented on ql/src/semmle/go/frameworks/stdlib/IoFs.qll
> +      exists(DataFlow::CallNode call, FuncDef def |
Worth a comment explaining that this is routing taint from WalkDir's arg0 to args 0 and 1 of the passed WalkDirFunc

2021-02-18 16:53 UTC, sauyon commented
>     * It would have been easier to review if this was split into separate commits for the different features being supported.

It ended up mostly being the FS model so I didn't bother splitting it out, but I can do.

>     * What is the binary file `go1.16`?

A result of me running `go build` to test builds, oops.

>     * I expected `File.Read()` to be modelled, but I guess it's covered by `io.Reader.Read()`. It might be worth putting a test for it with the other `io/fs` tests.

:+1: 

>     * Can you add a test for the change you made to `Os.qll`? I can't find any tests for the rest of that predicate, so I accept this might be difficult.

Indeed, tests didn't exist, but it's probably not really an excuse for me not to add tests.

2021-02-18 19:02 UTC, smowton commented
The go1.16 file is still there

2021-02-18 19:14 UTC, sauyon commented
I haven't yet pushed, I'm adding more tests and adding a model for `File.Read`, because it turns out because it's an interface method we don't consider it to implement `io.Reader.Read`.

2021-02-18 20:31 UTC, sauyon commented
Ok, everything should work now, including an additional (very confusing) change for a rename from `os.FileInfo` to `io/fs.FileInfo`.

2021-02-18 22:37 UTC, gagliardetto commented
@sauyon Did you use codebox, or that's handwritten following that code style?

2021-02-18 22:38 UTC, sauyon commented
Handwritten, have yet to get `codebox` running, hah.

2021-02-18 22:42 UTC, gagliardetto commented
Is it because of time constraints, or because it doesn't work?

2021-02-18 22:43 UTC, sauyon commented
I tried to run it once and the server errored; haven't gotten to figuring out why yet.

2021-02-18 22:45 UTC, gagliardetto commented
It could be used to diff the api of various packages between the current Go version and go1.16

2021-02-18 22:46 UTC, owen-mc commented on ql/test/extractor-tests/go1.16/embed.expected
> +ERROR: Query module does not have any queries in scope. (embed.ql:1,1-1)
You pushed a change before which fixed this error by adding something like `where exists(v.getDeclaration())`. Did that get lost somehow?

2021-02-18 22:52 UTC, sauyon commented on ql/test/extractor-tests/go1.16/embed.expected
> +ERROR: Query module does not have any queries in scope. (embed.ql:1,1-1)
Ugh. I think I pulled and git automatically rebased away some of my changes.

2021-02-18 22:53 UTC, sauyon commented
> It could be used to diff the api of various packages between the current Go version and go1.16

They list the relevant changes in the change notes. The only reason I had issues with `FileInfo` is because apparently we don't generate `hasQualifiedName` sensibly for alias types.

2021-02-18 23:05 UTC, gagliardetto commented
I'm not sure they go into extreme detail in the release notes. But then again, it might not be 100% important to have each and every function modeled.

2021-02-18 23:10 UTC, owen-mc approved these changes

2021-02-18 23:44 UTC, sauyon commented
I've gone through and modeled a few new changes that appeared in the patch notes; probably a lesson not to rely too heavily on Go tip.

2021-02-19 06:45 UTC, owen-mc reviewed
Should `NopCloser` from `io/ioutil` be modeled in `Io.qll` now that it's been moved there?

I see you didn't delete `IoIoutil.qll`. Is it needed to support using older versions of Go?

2021-02-19 14:29 UTC, sauyon commented
> Should `NopCloser` from `io/ioutil` be modeled in `Io.qll` now that it's been moved there?

Somehow missed this...

> I see you didn't delete `IoIoutil.qll`. Is it needed to support using older versions of Go?

It's deprecated and not removed (and won't be while Go is still in version 1).

2021-02-19 14:40 UTC, owen-mc approved these changes

2021-02-19 15:05 UTC, smowton approved these changes

2021-02-19 15:33 UTC, owen-mc commented on ql/src/semmle/go/frameworks/stdlib/Io.qll
> +      hasQualifiedName("io/ioutil", "NopCloser") and
```suggestion
      hasQualifiedName("io", "NopCloser") and
```

2021-02-19 15:58 UTC, sauyon commented on ql/src/semmle/go/frameworks/stdlib/Io.qll
> +      hasQualifiedName("io/ioutil", "NopCloser") and
:facepalm:

2021-02-19 16:02 UTC, sauyon commented
Well, at least the test I added worked.

2021-02-19 17:33 UTC, sauyon commented
Hm. @owen-mc mind testing the OS X issue on your machine on Monday?

2021-02-19 18:20 UTC, sauyon commented
I'd forgotten Chris also has a Mac, I've now solved the problem.

2021-02-23 16:16 UTC, merged