Highlight error messages in CI
github/codeql-go pull request #501
Opened 2021-03-11 15:09 UTC by owen-mc

Copied problem-matchers from github/semmle-code, which is used for
running CI for github/codeql.

2021-03-11 15:11 UTC, owen-mc commented
I'm not familiar with these things, so I may have made some basic errors. I copied all the problem-matchers from semmle-code except the ones for gcc and msvc, which I assume we don't need. Can I also get rid of the odasa one? Do we need the others?

Another question: have I put the new step in the right places in `codeqltest.yaml`?

2021-03-11 15:41 UTC, criemen requested changes
A minor comment, and a request for a repo admin:

Can somebody enable actions debugging (following the steps here):
https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-runner-diagnostic-logging
Then, we can see in the log outputs whether the problem matchers have been successfully enabled on all 3 platforms.

2021-03-11 15:41 UTC, criemen commented on .github/problem-matchers/odasa-qltest.json
> +{
Yep, you don't need that file :)

2021-03-11 15:41 UTC, criemen commented on .github/workflows/codeqltest.yml
> +      run: 'find .github/problem-matchers -name \*.json -exec echo "::add-matcher::{}" \;'
It seems from your `Makefile` that you already have find and bash installed on the Windows testrunner.
Thus it ought to work.

2021-03-11 15:43 UTC, sauyon commented
> Can somebody enable actions debugging...

Should be done.

2021-03-11 15:58 UTC, owen-mc commented
I've repushed, after @sauyon turned actions debugging on, so the logs should contain the information you are looking for

2021-03-11 16:59 UTC, criemen commented
@sauyon I am really sorry, I was to quick in skimming the doc :|
What I meant is actions step debugging, not actions runner debugging, i.e. `ACTIONS_STEP_DEBUG=true`.

2021-03-11 17:13 UTC, owen-mc commented
I've set that now. I'll repush in a minute.

2021-03-12 09:32 UTC, owen-mc commented
@criemen Do the logs have the right info in them now?

2021-03-12 10:04 UTC, criemen approved these changes
LGTM!

Debug logs are not included here, because they are enabled via actions secrets, and pull requests from other repos don't get access to the actions secrets...
I re-pushed this commit to a branch from inside the repo, re-run actions on that and the logs look exactly like they should.

2021-03-12 10:51 UTC, smowton approved these changes
Proxying @criemen's approval

2021-03-12 15:22 UTC, merged