CWE-1004: Sensitive cookie without HttpOnly
github/codeql-go pull request #529
Opened 2021-04-25 20:37 UTC by edvraa

2021-04-26 10:12 UTC, edvraa commented
> Does / will this have a corresponding bounty application?

Yes, was planning if it is merged. Are there any differences? Does bounty application speeds up review?

2021-04-26 10:16 UTC, smowton commented
No particular speed difference but it affects who does the work. In this case you should apply before merging, and you'll get accuracy comments from the security lab team.

2021-04-26 10:21 UTC, edvraa commented
Sorry, didn't know that. Just created it.

2021-04-26 16:11 UTC, owen-mc requested changes

2021-04-26 16:11 UTC, owen-mc commented on ql/src/experimental/CWE-1004/AuthCookie.qll
> +      pred = w.getRhs() and
```suggestion
      w.writesField(base, f, pred) and
```

2021-04-26 16:11 UTC, owen-mc commented on ql/src/experimental/CWE-1004/CookieWithoutHttpOnly.ql
> +    exists(AuthCookieNameConfiguration cookieNameCfg | cookieNameCfg.hasFlow(source, sink)) and
I think it would be easier to read if you combined all three `exists` into one. Alternatively you could use `any` for the two configurations, as they are each only referenced once.

2021-04-26 16:11 UTC, owen-mc commented on ql/src/experimental/CWE-1004/CookieWithoutHttpOnly.ql
> +where
I think each of the three disjuncts should be pulled out into a separate predicate (in this file), to make this `where` clause simpler to read.

2021-04-28 09:07 UTC, owen-mc requested changes

2021-04-28 09:07 UTC, owen-mc commented on ql/src/experimental/CWE-1004/CookieWithoutHttpOnly.ql
> +      valSrc.asExpr().getBoolValue() = false
This could be made simpler using `getAPredecessor*()`, though actually I think you should make it a full configuration to get a path for the query.

2021-04-28 09:07 UTC, owen-mc commented on ql/src/experimental/CWE-1004/CookieWithoutHttpOnly.ql
> +select expr, "Cookie attribute 'HttpOnly' is not set to true."
I think it would be better if we reported the whole path to the user, rather than just one end. Change `@kind problem` to `@kind path-problem`, adjust the three predicates to take `source` and `sink` and change the query to the below.
```suggestion
from DataFlow::PathNode source, DataFlow::PathNode sink
where
  isNetHttpCookieFlow(source, sink) or
  isGinContextCookieFlow(source, sink) or
  isGorillaSessionsCookieFlow(source, sink)
select sink.getNode(), source, sink, "Cookie attribute 'HttpOnly' is not set to true."
```

2021-04-30 11:01 UTC, edvraa commented
Path tracking ended up as a big change, but let's think big - global flow tracking :) There is one odd thing though. A query like:
```ql
from BoolToGorillaSessionOptionsTrackingConfiguration cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select sink.getNode(), source, sink, "Cookie attribute 'HttpOnly' is not set to true."
```
gives me odd path:
![image](https://user-images.githubusercontent.com/80588099/116686200-25ea7400-a9bc-11eb-83b5-3ec097b483c2.png)
![image](https://user-images.githubusercontent.com/80588099/116686022-e7ed5000-a9bb-11eb-881c-12af8c79452e.png)
The sink and the source are good, but the intermediate path is funny. Do I do something wrong?

2021-04-30 13:17 UTC, owen-mc commented
No, you didn't do anything wrong. The first path is fine, though some steps are skipped that you might expect to see. The extra paths are a quirk of how to we track data flow. I think this was explained [here](https://github.com/github/codeql-go/issues/515#issuecomment-806597731).

2021-05-05 13:56 UTC, owen-mc requested changes

2021-05-05 13:56 UTC, owen-mc commented on ql/src/experimental/CWE-1004/CookieWithoutHttpOnly.ql
> +predicate isNetHttpCookieFlow(DataFlow::PathNode source, DataFlow::PathNode sink) {
Please can you add documentation to all of the public elements, such as these three predicates? The [style guide](https://github.com/github/codeql/blob/master/docs/qldoc-style-guide.md) might be helpful.

2021-05-11 14:58 UTC, owen-mc requested changes
Great - it's so much easier to read with the comments! I understand a lot better what's going on now. I only had time to do a partial review. Most of my comments are about slightly better ways of doing things, e.g. using data flow nodes instead of exprs, but they will make things a lot more readable.

2021-05-11 15:00 UTC, owen-mc commented
Oh, and I forgot to mention that you need to regenerate the `.expected` file because you reformatted the `.go` file and that change the line numbers. (This isn't a problem for tests that use InlineExpectations, as you put comments in the code to indicate where results are expected, so they move with the reformatting.)

2021-05-12 20:33 UTC, edvraa commented on ql/src/experimental/CWE-1004/AuthCookie.qll
> +        c.getAnArgument() = nameArg.asExpr()
My mistake

2021-05-13 11:42 UTC, edvraa commented on ql/src/experimental/CWE-1004/AuthCookie.qll
> +    )
For some reason `NewCookieStore` is translated to `CallNode` instead of `MethodCallNode`

2021-05-13 16:38 UTC, edvraa commented on ql/src/experimental/CWE-1004/AuthCookie.qll
> +private class NameToNetHttpCookieTrackingConfiguration extends TaintTracking2::Configuration {
I got rid of `NetHttpCookieTrackingConfiguration`. Please take a look.
I think it is unavoidable to track some paths twice because there are two taints: sensitive name and `false` set to `HttpOnly`. There is one sink - `SetCookie`. Here both taints are checked.
In the current implementation `HasFlowPath` is used only once. The second taint is tracked with `HasFlow`. Does it eliminate the concern?

2021-05-14 10:36 UTC, owen-mc commented on ql/src/experimental/CWE-1004/AuthCookie.qll
> +    )
Oops, my mistake, it is indeed a function rather than a method.

2021-05-14 10:47 UTC, owen-mc commented on ql/src/experimental/CWE-1004/AuthCookie.qll
> +private class NameToNetHttpCookieTrackingConfiguration extends TaintTracking2::Configuration {
If I've understood correctly, when there is a `BoolToNetHttpCookieTrackingConfiguration` with flow then the paths you are interested in are Y-shaped. You have one flow from a sensitive name to a struct literal to a `SetCookie`. And you have another flow from a `false` to a struct literal to a `SetCookie`.  Oh, I see why what I said doesn't work. Given the first flow, you don't get access to the struct literal in the middle of it to then use it as the sink for the second flow. Okay, this is a totally reasonable way to do it then.

2021-05-14 10:50 UTC, owen-mc commented on ql/src/experimental/CWE-1004/AuthCookie.qll
> +    )
I still think this would be an improvement - make it part of the definition of `SetCookieSink` that a sensitive name flows to it (and maybe change its name to reflect that). This would improve performance and wouldn't change the results at all.

2021-05-14 13:10 UTC, owen-mc submitted a review, later dismissed
Looking good. A few more comments.

Also, I should say that this advice about staying at the level of `DataFlow::Node`s is specific to the CodeQL libraries for Go. If you write a query for another language then it will be different.

2021-05-14 13:10 UTC, owen-mc commented on ql/src/experimental/CWE-1004/CookieWithoutHttpOnly.ql
> +        cfg.hasFlow(source.getNode(), setCookieSink.getNode()) and
This gives the result but doesn't show the path when you run the query in VS code or LGTM. The reason is that a `PathNode` is a `Node` with some extra information about the path, and that information is determined by calling `hasFlowPath(source, sink)` on some configuration. You need to think about what path you want to show in each case, and make sure the parameters `source` and `sink` are set to the beginning and end of that path. This applies for most the cases in this query.

2021-05-14 13:11 UTC, owen-mc commented
Oh, and my unresolved comment about changing the definition of `SetCookieSink` from the previous review still applies.

2021-05-24 15:50 UTC, edvraa commented on ql/src/experimental/CWE-1004/CookieWithoutHttpOnly.ql
> +        cfg.hasFlow(source.getNode(), setCookieSink.getNode()) and
I have made the changes, but it is odd edges and nodes didn't change in the unit tests. Could you please check if it is working now as expected?

2021-05-24 16:28 UTC, edvraa commented
> Oh, and my unresolved comment about changing the definition of `SetCookieSink` from the previous review still applies.

Do you mean [this one](https://github.com/github/codeql-go/pull/529#discussion_r630157079)?
I tried something like that:
```
private class SetCookieSink extends DataFlow::Node {
  SetCookieSink() {
    exists(DataFlow::CallNode cn |
      cn.getTarget().hasQualifiedName(package("net/http", ""), "SetCookie") and
      this = cn.getArgument(1) and
      exists(NameToNetHttpCookieTrackingConfiguration cfg, DataFlow::Node source |
        cfg.hasFlow(source, this)
      )
    )
  }
}

class NameToNetHttpCookieTrackingConfiguration extends TaintTracking2::Configuration {
  NameToNetHttpCookieTrackingConfiguration() { this = "NameToNetHttpCookieTrackingConfiguration" }

  override predicate isSource(DataFlow::Node source) { isAuthVariable(source.asExpr()) }

  override predicate isSink(DataFlow::Node sink) { sink instanceof DataFlow::Node }

  override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
    exists(StructLit sl |
      sl.getType() instanceof NetHttpCookieType and
      getValueForFieldWrite(sl, "Name") = pred and
      sl = succ.asExpr()
    )
  }
}
```
The sink predicate becomes odd, otherwise it is non monotonic recursion...
This gives `PathNode is not compatible with PathNode`. If I change `TaintTracking2` to `TaintTracking` it is again non monotonic.
I use `NameToNetHttpCookieTrackingConfiguration` separately in `isNetHttpCookieFlow` to the path from sensitive name to sink in case no boolean is assigned.

2021-06-08 10:47 UTC, owen-mc commented on ql/src/experimental/CWE-1004/CookieWithoutHttpOnly.ql
> +        cfg.hasFlow(source.getNode(), setCookieSink.getNode()) and
I'm pretty sure that that is okay

2021-06-08 10:59 UTC, owen-mc reviewed
Hmm, it seems [that comment](https://github.com/github/codeql-go/pull/529#discussion_r630157079) doesn't make sense any more. Oh well.

2021-06-17 05:53 UTC, owen-mc approved these changes

2021-06-17 08:23 UTC, merged