Add Xorm support
github/codeql-go pull request #534
Opened 2021-05-06 06:27 UTC by sn00pyd0g3

Issue: #533 
Xorm Document: https://pkg.go.dev/xorm.io/xorm
Added support for xorm framework, which is similar to gorm

2021-05-11 11:43 UTC, sauyon requested changes
Some relatively minor comments.

2021-05-11 11:43 UTC, sauyon commented on ql/test/library-tests/semmle/go/frameworks/SQL/Xorm/xorm.expected
> +| xorm.go:19:16:19:24 | untrusted |
Could you convert this test into an `InlineExpectationsTest`? If you grep the repo for that you should find some examples.

2021-05-11 11:43 UTC, sauyon commented on ql/test/library-tests/semmle/go/frameworks/SQL/Xorm/vendor/github.com/go-xorm/xorm/stub.go
> +// Code generated by depstubber. DO NOT EDIT.
Seems like we're missing a license here.

2021-05-11 11:43 UTC, sauyon commented on ql/src/semmle/go/frameworks/SQL.qll
> +        this.getType().getUnderlyingType() instanceof StringType and
This check should be unnecessary because you're already specifying which arguments are considered.

2021-05-11 11:43 UTC, sauyon commented on ql/src/semmle/go/frameworks/SQL.qll
> +        meth.hasQualifiedName(package, type, name) and
You could probably get rid of  `package` and just slot in `packagePath()`.

2021-05-13 15:21 UTC, smowton commented on ql/test/library-tests/semmle/go/frameworks/SQL/Xorm/xorm.expected
> +| xorm.go:19:16:19:24 | untrusted |
Here's an example of how to do this: https://github.com/github/codeql-go/blob/466d87684d77b40cbba6a3753c16522158c2edf6/ql/test/library-tests/semmle/go/frameworks/Yaml/tests.ql

And here is the .go file with comments indicating the expected results using specially structured comments: https://github.com/github/codeql-go/blob/466d87684d77b40cbba6a3753c16522158c2edf6/ql/test/library-tests/semmle/go/frameworks/Yaml/yaml.go

For example here you could define `hasActualResult` to find a `SQL::QueryString` and report its source file and line number.

2021-05-14 02:18 UTC, sn00pyd0g3 commented on ql/test/library-tests/semmle/go/frameworks/SQL/Xorm/xorm.expected
> +| xorm.go:19:16:19:24 | untrusted |
ok, got it

2021-06-27 14:04 UTC, sn00pyd0g3 commented on ql/test/library-tests/semmle/go/frameworks/SQL/Xorm/vendor/github.com/go-xorm/xorm/stub.go
> +// Code generated by depstubber. DO NOT EDIT.
I don’t understand what you mean, this file is automatically generated, do I need to add anything?

2021-08-04 09:44 UTC, sauyon commented on ql/test/library-tests/semmle/go/frameworks/SQL/Xorm/vendor/github.com/go-xorm/xorm/stub.go
> +// Code generated by depstubber. DO NOT EDIT.
Sorry, I'd forgotten about this. You just need to grab the license file from the project and put it alongside the stub file.

2021-08-23 15:16 UTC, sauyon commented
Closing in favor of #559.

2021-08-23 15:16 UTC, closed without merging