Accelerating go-extractor by using 'go list -deps' instead of just 'go list'
github/codeql-go pull request #554
Opened 2021-07-25 06:45 UTC by xhd2015

just run `go list` once

2021-07-25 06:56 UTC, xhd2015 commented
Background is that, I hava a project that depends on 980 packages, each time I run `codeql database create ...` I see most of the time cost is contributed by running `go list` to retrieve package and module directory once for each package.
I have counted how much time actually just `go list` consumes, and here is the log:
```bash
[2021-07-25 13:24:58] [build-stderr] 2021/07/25 13:24:58 Running go list.
[2021-07-25 13:51:34] [build-stderr] 2021/07/25 13:51:34 Done running go list, all pkgRoots are:980
```

The log shows that `go list` for all packages consumed `26 minutes`.

here is the testing code added to `extractor/extractor.go`:
```go
	log.Printf("Running go list.")
	packages.Visit(pkgs, func(pkg *packages.Package) bool {
		return true
	}, func(pkg *packages.Package) {
		if _, ok := pkgRoots[pkg.PkgPath]; !ok {
			mdir := util.GetModDir(pkg.PkgPath, modFlags...)
			pdir := util.GetPkgDir(pkg.PkgPath, modFlags...)
			// GetModDir returns the empty string if the module directory cannot be determined, e.g. if the package
			// is not using modules. If this is the case, fall back to the package directory
			if mdir == "" {
				mdir = pdir
			}
			pkgRoots[pkg.PkgPath] = mdir
			pkgDirs[pkg.PkgPath] = pdir
		}
	})
	log.Printf("Done running go list, all pkgRoots are:%d", len(pkgRoots))
```


With `go list -deps`, the time cost is significantly reduced, here is the log:
```bash
[2021-07-25 13:59:40] [build-stderr] 2021/07/25 13:59:40 Running go list deps.
[2021-07-25 13:59:40] [build-stderr] 2021/07/25 13:59:40 Running cmd: /usr/local/go/bin/go list -e -f {{.ImportPath}}{{"\n"}}{{.Dir}}{{"\n"}}{{if .Module}}{{.Module.Dir}}{{else}}<nil>{{end}} -deps ./...
[2021-07-25 13:59:42] [build-stderr] 2021/07/25 13:59:42 Done running go list deps,resolved 980 packags
```

just `2 seconds`.

2021-07-26 10:01 UTC, smowton commented on extractor/util/util.go
> +// GetPkgModDir gets the absolute directory of the module and the package dir containing the package with path
Update docstring

2021-07-26 10:01 UTC, smowton commented on extractor/extractor.go
> +	log.Printf("Running go list deps.")
```suggestion
	log.Printf("Running go list to resolve package and module directories.")
```

2021-07-26 10:01 UTC, smowton commented on extractor/extractor.go
> +	log.Printf("Done running go list deps,resolved %d packags", len(pkgMod))
```suggestion
	log.Printf("Done running go list deps: resolved %d packages", len(pkgMod))
```

2021-07-26 10:01 UTC, smowton commented on extractor/extractor.go
> +			log.Fatalf("Warning pkg dir is not resolved:%s", pkg.PkgPath)
If it's a warning, skip the package. Otherwise this is worse than a warning.

2021-07-27 02:39 UTC, xhd2015 commented on extractor/extractor.go
> +			log.Fatalf("Warning pkg dir is not resolved:%s", pkg.PkgPath)
Can we simply remove this block of code? Because the original code just ignores if `go list` fails to resolve its directory, no warning or skipping.

2021-07-27 04:34 UTC, sauyon requested changes

2021-07-27 04:34 UTC, sauyon commented on extractor/extractor.go
> +	pkgMod, err := util.GetPkgModDir(patterns, true, modFlags...)
I think I'd like to refactor `pkgMod` to be a map of `PkgMod` (I'd prefer to name it `PkgDirs` as noted below) to begin with; no sense constructing a slice and then transforming it to a map immediately.

2021-07-27 04:34 UTC, sauyon commented on extractor/util/util.go
>  }
I think it makes sense to change `runGoList` to take a slice of patterns as well and not rename `runGoListWithEnv` for consistency.

2021-07-27 04:34 UTC, sauyon commented on extractor/util/util.go
> +// `patterns` can include plain package path, relative package or the special package `./...`,see `go help packages` for detailed information.
```suggestion
// pattern `patterns`, with environment variables `additionalEnv`, which is a slice of strings in the format `NAME=VALUE`.
```

2021-07-27 04:34 UTC, sauyon commented on extractor/util/util.go
> +type PkgMod struct {
Would prefer this be called `PkgDirs` or maybe `PkgInfo`. `PkgPath` isn't necessary.

2021-07-27 04:34 UTC, sauyon commented on extractor/util/util.go
> +	mod, err := runGoListPatternWithEnv("{{.ImportPath}}{{\"\\n\"}}{{.Dir}}{{\"\\n\"}}{{if .Module}}{{.Module.Dir}}{{else}}<nil>{{end}}", patterns, []string{"GO111MODULE=on"}, flags...)
We should use `-json` here instead of any separators; the only character that's invalid in a Unix path is the null byte, which I don't think we can make `go list` output (`{{"\0"}}` gives me `invalid syntax`).

Also, separately, I think I should have made this use `-e`; can you do that now?

2021-07-27 04:34 UTC, sauyon commented on extractor/util/util.go
> +			log.Printf("Warning: unable to make %s absolute: %s", pkgs[idx+1], err.Error())
Don't continue the loop (just the program) here or below; even if that fails you still want to keep the values around.

It's also worth noting you haven't run `idx += 3` here.

2021-07-27 04:34 UTC, sauyon commented on extractor/util/util.go
> +func getAbsDir(outputDir string) (string, error) {
This function isn't very well named, but I think it should be redundant if `-json` is used anyway.

2021-07-27 06:29 UTC, xhd2015 commented on extractor/util/util.go
> +	mod, err := runGoListPatternWithEnv("{{.ImportPath}}{{\"\\n\"}}{{.Dir}}{{\"\\n\"}}{{if .Module}}{{.Module.Dir}}{{else}}<nil>{{end}}", patterns, []string{"GO111MODULE=on"}, flags...)
Agreed. I evaluated the `-json` output of my project(with 980 packages),  it consumed `3.5s`, and size of the generated json is `5MB`. It seems acceptable.
And also note that `-json` outputs a stream of json object, no an array of json object. Example:
```json
{
	"Dir": "/Users/bytedance/installed/go/src/internal/cpu",
	"ImportPath": "internal/cpu",
         "...":"..."
}
{
	"Dir": "/Users/bytedance/installed/go/src/unsafe",
	"ImportPath": "unsafe",
        "...":"..."
}
```

2021-07-27 06:58 UTC, xhd2015 commented on extractor/extractor.go
> +	pkgMod, err := util.GetPkgModDir(patterns, true, modFlags...)
It's now a `map[string]*PkgMod`, not a slice.

2021-07-27 07:52 UTC, xhd2015 commented
@smowton @sauyon Thanks for both your commenting!

2021-07-28 04:47 UTC, sauyon commented on extractor/extractor.go
> +	pkgMod, err := util.GetPkgModDir(patterns, true, modFlags...)
Ah, indeed. No need to split it into two maps below, then.

2021-08-09 14:53 UTC, sauyon commented on extractor/extractor.go
> +		pkgDirs[pkgPath] = pdir
Could you just remove these two maps and use `pkgsInfo` below?

2021-08-12 06:35 UTC, sauyon commented
@smowton @xhd2015 I've pushed the changes I wanted; this still needs a rebase over main, which I won't do for now in case you'd like to do something with the current history.

2021-08-12 08:06 UTC, smowton commented
Test it with a simulated lgtm.com upgrade then merge if good?

2021-08-19 07:20 UTC, xhd2015 commented
@sauyon I shall commit no more changes to it, it's ok to rebase this branch over main.  As for the test, I don't know how to do that.

2021-08-19 10:25 UTC, smowton commented
Sounds good, the test is for @sauyon to do

2021-09-02 07:16 UTC, sauyon commented
@smowton Made some changes based on the LGTM tests; had about 5 projects fail because of a `SEGV` that I fix in the last commit, but otherwise I think this is good to go.

2021-09-02 08:52 UTC, smowton commented
Looks like there's currently a build failure. Have you manually retested those projects getting a segfault?

2021-09-02 17:11 UTC, smowton approved these changes

2021-09-02 17:27 UTC, sauyon commented
This does now appear to work.

2021-09-02 19:32 UTC, sauyon approved these changes

2021-09-02 19:32 UTC, merged