Add a query suite for new experimental "developer happiness" queries
github/codeql-go pull request #561
Opened 2021-08-16 17:06 UTC by sampart

These are the queries added in https://github.com/github/codeql-go/pull/558.

Note that when the qlpack name changes, this suite will need updating.

I wasn't sure if this was testable prior to merging, so any suggestions there welcome.

2021-08-16 20:47 UTC, smowton commented
Fine by me if others are ok with the name

2021-08-16 20:48 UTC, smowton approved these changes
Merge when you're happy

2021-08-16 20:51 UTC, adityasharad requested changes

2021-08-16 20:51 UTC, adityasharad commented on ql/src/codeql-suites/go-developer-happiness.qls
> +    id: go/examples/gorm-error-not-checked
I tried this out and I believe you need three separate `include` instructions to reference each ID. Otherwise you only get the last ID in the constraint map.
```suggestion
- include:
    id: go/examples/database-call-in-loop
- include:
    id: go/examples/deferinloop
- include:
    id: go/examples/gorm-error-not-checked
```


A shorter but arguably murkier alternative is to use a regex:
```suggestion
- include:
    id: /go/examples/(database-call-in-loop|deferinloop|gorm-error-not-checked)/
```

2021-08-17 08:53 UTC, sampart commented on ql/src/codeql-suites/go-developer-happiness.qls
> +    id: go/examples/gorm-error-not-checked
Thank you!

2021-08-17 15:34 UTC, adityasharad approved these changes

2021-08-17 18:45 UTC, merged